import { StandardStatus } from "@/backend";
import type { SafetyStandard, StandardCategory } from "@/backend";

export const SAMPLE_STANDARDS: SafetyStandard[] = [
  {
    id: "osha-1926-20",
    category: "OSHA" as StandardCategory,
    code: "1926.20",
    title: "General Safety and Health Provisions",
    summary:
      "Responsibilities, accident prevention, and safety training requirements for construction employers.",
    applicableTrades: ["All"],
    csiDivisions: ["00", "01"],
    state: undefined,
    relatedStandards: ["1926.21", "1926.23"],
    status: StandardStatus.Active,
  },
  {
    id: "osha-1926-21",
    category: "OSHA" as StandardCategory,
    code: "1926.21",
    title: "Safety Training and Education",
    summary:
      "Employer obligations to provide safety training, hazard recognition, and emergency procedures.",
    applicableTrades: ["All"],
    csiDivisions: ["00", "01"],
    state: undefined,
    relatedStandards: ["1926.20", "1926.23"],
    status: StandardStatus.Active,
  },
  {
    id: "osha-1926-451",
    category: "OSHA" as StandardCategory,
    code: "1926.451",
    title: "Scaffolding — General Requirements",
    summary:
      "Design, construction, and use of scaffolds including load capacity, platform construction, and access.",
    applicableTrades: ["Masonry", "Painting", "General Labor"],
    csiDivisions: ["04", "09"],
    state: undefined,
    relatedStandards: ["1926.452", "1926.453"],
    status: StandardStatus.Active,
  },
  {
    id: "osha-1926-501",
    category: "OSHA" as StandardCategory,
    code: "1926.501",
    title: "Duty to Have Fall Protection",
    summary:
      "Requirements for fall protection systems at heights of 6 feet or more in construction.",
    applicableTrades: ["Roofing", "Framing", "Steel Erection"],
    csiDivisions: ["05", "07", "13"],
    state: undefined,
    relatedStandards: ["1926.502", "1926.503"],
    status: StandardStatus.Active,
  },
  {
    id: "osha-1926-650",
    category: "OSHA" as StandardCategory,
    code: "1926.650",
    title: "Excavations — General Requirements",
    summary:
      "Protective systems for trenches and excavations, soil classification, and competent person duties.",
    applicableTrades: ["Excavation", "Utilities", "Concrete"],
    csiDivisions: ["02", "03", "33"],
    state: undefined,
    relatedStandards: ["1926.651", "1926.652"],
    status: StandardStatus.Active,
  },
  {
    id: "osha-1926-703",
    category: "OSHA" as StandardCategory,
    code: "1926.703",
    title: "Concrete and Masonry Construction",
    summary:
      "Formwork, shoring, precast concrete, and lift-slab operations safety requirements.",
    applicableTrades: ["Concrete", "Masonry", "Formwork"],
    csiDivisions: ["03", "04"],
    state: undefined,
    relatedStandards: ["1926.701", "1926.702"],
    status: StandardStatus.Active,
  },
  {
    id: "ansi-a10-1",
    category: "ANSI" as StandardCategory,
    code: "A10.1",
    title: "Pre-Project and Pre-Task Safety Planning",
    summary:
      "Guidelines for developing safety plans before project commencement and task execution.",
    applicableTrades: ["All"],
    csiDivisions: ["00", "01"],
    state: undefined,
    relatedStandards: ["A10.2", "A10.3"],
    status: StandardStatus.Active,
  },
  {
    id: "ansi-a10-6",
    category: "ANSI" as StandardCategory,
    code: "A10.6",
    title: "Demolition Operations",
    summary:
      "Safety requirements for demolition, deconstruction, and dismantling of structures.",
    applicableTrades: ["Demolition", "General Labor"],
    csiDivisions: ["02", "31"],
    state: undefined,
    relatedStandards: ["A10.1", "A10.33"],
    status: StandardStatus.Active,
  },
  {
    id: "ansi-a10-32",
    category: "ANSI" as StandardCategory,
    code: "A10.32",
    title: "Personal Fall Protection Equipment",
    summary:
      "Specifications for fall arrest systems, body harnesses, lanyards, and anchorages.",
    applicableTrades: ["Roofing", "Steel Erection", "Scaffolding"],
    csiDivisions: ["05", "07", "13"],
    state: undefined,
    relatedStandards: ["A10.33", "1926.501"],
    status: StandardStatus.Active,
  },
  {
    id: "ieee-1584",
    category: "IEEE" as StandardCategory,
    code: "1584",
    title: "Arc Flash Hazard Calculation",
    summary:
      "Methods for calculating arc flash incident energy and determining PPE requirements.",
    applicableTrades: ["Electrical", "MEP"],
    csiDivisions: ["26", "25"],
    state: undefined,
    relatedStandards: ["IEEE 3003", "NFPA 70E"],
    status: StandardStatus.Active,
  },
  {
    id: "ieee-3003",
    category: "IEEE" as StandardCategory,
    code: "3003",
    title: "Recommended Practice for Grounding",
    summary:
      "Grounding and bonding practices for industrial and commercial power systems.",
    applicableTrades: ["Electrical", "MEP"],
    csiDivisions: ["26", "25"],
    state: undefined,
    relatedStandards: ["IEEE 1584", "NEC Article 250"],
    status: StandardStatus.Active,
  },
  {
    id: "nccer-core",
    category: "NCCER" as StandardCategory,
    code: "NCCER-CORE",
    title: "NCCER Core Curriculum — Construction Fundamentals",
    summary:
      "Basic safety, construction math, hand tools, power tools, and employability skills.",
    applicableTrades: ["All"],
    csiDivisions: ["00"],
    state: "Federal",
    relatedStandards: ["NCCER-CARP-1", "NCCER-ELEC-1"],
    status: StandardStatus.Active,
  },
  {
    id: "nccer-carp-1",
    category: "NCCER" as StandardCategory,
    code: "NCCER-CARP-1",
    title: "Carpentry Level 1 — Fundamentals",
    summary:
      "Orientation to the trade, building materials, fasteners, adhesives, and hand/power tools.",
    applicableTrades: ["Carpentry", "Framing"],
    csiDivisions: ["06"],
    state: "Federal",
    relatedStandards: ["NCCER-CORE", "NCCER-CARP-2"],
    status: StandardStatus.Active,
  },
  {
    id: "nccer-elec-1",
    category: "NCCER" as StandardCategory,
    code: "NCCER-ELEC-1",
    title: "Electrical Level 1 — Introduction",
    summary:
      "Electrical safety, circuits, theory, National Electrical Code introduction, and device installation.",
    applicableTrades: ["Electrical", "MEP"],
    csiDivisions: ["26"],
    state: "Federal",
    relatedStandards: ["NCCER-CORE", "NCCER-ELEC-2"],
    status: StandardStatus.Active,
  },
  {
    id: "ibc-2021",
    category: "IBC" as StandardCategory,
    code: "IBC-2021",
    title: "International Building Code 2021",
    summary:
      "Comprehensive building code covering structural, fire safety, egress, and accessibility requirements.",
    applicableTrades: ["All"],
    csiDivisions: ["00", "01", "02"],
    state: undefined,
    relatedStandards: ["IRC-2021", "IFC-2021"],
    status: StandardStatus.Active,
  },
  {
    id: "ibc-ca-2022",
    category: "IBC" as StandardCategory,
    code: "IBC-CA-2022",
    title: "California Building Code 2022",
    summary:
      "California-specific amendments to the IBC including seismic design, energy efficiency, and accessibility.",
    applicableTrades: ["All"],
    csiDivisions: ["00", "01", "02"],
    state: "California",
    relatedStandards: ["IBC-2021", "CBC-Title-24"],
    status: StandardStatus.Active,
  },
  {
    id: "ibc-tx-2021",
    category: "IBC" as StandardCategory,
    code: "IBC-TX-2021",
    title: "Texas Building Code 2021",
    summary:
      "Texas amendments to the IBC including windstorm provisions and energy code requirements.",
    applicableTrades: ["All"],
    csiDivisions: ["00", "01", "02"],
    state: "Texas",
    relatedStandards: ["IBC-2021", "TDI-Windstorm"],
    status: StandardStatus.Active,
  },
  {
    id: "osha-1926-95",
    category: "OSHA" as StandardCategory,
    code: "1926.95",
    title: "Criteria for Personal Protective Equipment",
    summary:
      "Selection, use, and maintenance of PPE including head, eye, face, foot, and hand protection.",
    applicableTrades: ["All"],
    csiDivisions: ["00", "01"],
    state: undefined,
    relatedStandards: ["1926.96", "1926.100"],
    status: StandardStatus.Active,
  },
  {
    id: "osha-1926-1053",
    category: "OSHA" as StandardCategory,
    code: "1926.1053",
    title: "Stairways and Ladders",
    summary:
      "Design, construction, and use of stairways and ladders on construction sites.",
    applicableTrades: ["All"],
    csiDivisions: ["00", "01"],
    state: undefined,
    relatedStandards: ["1926.1050", "1926.1051"],
    status: StandardStatus.Active,
  },
  {
    id: "ansi-a10-33",
    category: "ANSI" as StandardCategory,
    code: "A10.33",
    title: "Safety and Health Program Requirements",
    summary:
      "Comprehensive safety and health program elements for construction and demolition operations.",
    applicableTrades: ["All"],
    csiDivisions: ["00", "01"],
    state: undefined,
    relatedStandards: ["A10.1", "A10.6"],
    status: StandardStatus.Active,
  },
];

export const US_STATES = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];

export const ALL_ROLES = [
  "Owner",
  "Designer",
  "Architect",
  "CivilEngineer",
  "MechanicalEngineer",
  "SpecialtyEngineer",
  "ConstructionManager",
  "Contractor",
  "ProjectEngineer",
  "EHSRepresentative",
  "SafetyEngineer",
  "SafetyInspector",
] as const;

export const COMPLIANCE_ACCESS_ROLES = [
  "Owner",
  "Designer",
  "Architect",
  "CivilEngineer",
  "MechanicalEngineer",
  "SpecialtyEngineer",
  "ConstructionManager",
  "Contractor",
  "ProjectEngineer",
  "EHSRepresentative",
  "SafetyEngineer",
  "SafetyInspector",
];

export const EHS_ROLES = [
  "EHSRepresentative",
  "SafetyEngineer",
  "SafetyInspector",
];

export const SIGN_OFF_REQUIRED_ROLES = ["Owner", "Designer", "Architect"];

export const SAFETY_SIGN_OFF_ROLES = ["SafetyEngineer", "SafetyInspector"];
