/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIAFormEntry {
  'id' : string,
  'submittedByRole' : string,
  'submittedAt' : bigint,
  'formType' : FormType,
  'lastModified' : bigint,
  'sessionId' : string,
  'fieldData' : Array<[string, string]>,
}
export type AccessControlMode = { 'RoleGated' : null } |
  { 'ProjectManagerOnly' : null };
export interface AdminRole {
  'assignedAt' : bigint,
  'assignedBy' : Principal,
  'assignedPrincipal' : Principal,
}
export interface AppSettings {
  'activeCategoryId' : [] | [string],
  'projectManagerId' : [] | [string],
  'rsMeansSettings' : RSMeansSettings,
  'activeSubtopicId' : [] | [string],
  'accessControlMode' : AccessControlMode,
}
export type ApplyTemplateResult = { 'ok' : { 'phasesCreated' : bigint } } |
  { 'err' : string };
export interface BankAccount {
  'nextPayoutDate' : [] | [string],
  'routingNumber' : string,
  'accountHolderName' : string,
  'connectedToStripe' : boolean,
  'isVerified' : boolean,
  'accountNumberLast4' : string,
}
export type BaselineType = { 'crashed' : null } |
  { 'original' : null };
export interface CPMPhaseInput {
  'id' : string,
  'name' : string,
  'endOffset' : number,
  'dependencies' : Array<string>,
  'startOffset' : number,
}
export interface CancellationRequest {
  'id' : string,
  'status' : CancellationRequestStatus,
  'email' : string,
  'subscriberPrincipal' : Principal,
  'requestedAt' : bigint,
  'reason' : string,
}
export type CancellationRequestStatus = { 'pending' : null } |
  { 'denied' : null } |
  { 'approved' : null };
export interface ComplianceItemShared {
  'id' : string,
  'status' : ComplianceStatus,
  'notes' : string,
  'standardId' : string,
  'checkedAt' : bigint,
  'checkedBy' : string,
  'severity' : ComplianceSeverity,
  'phaseId' : string,
}
export type ComplianceSeverity = { 'None' : null } |
  { 'Critical' : null } |
  { 'Major' : null } |
  { 'Minor' : null };
export type ComplianceStatus = { 'NA' : null } |
  { 'NonCompliant' : null } |
  { 'Compliant' : null };
export interface CostCode {
  'id' : bigint,
  'area' : string,
  'cost' : number,
  'projectNumber' : string,
  'operation' : string,
  'csiCode' : string,
  'distribution' : string,
  'csiDivision' : string,
  'phaseId' : bigint,
}
export interface CostCodeBreakdown {
  'cumulativeCost' : number,
  'csiCode' : string,
  'csiDivision' : string,
}
export type CostCodeId = bigint;
export interface CostCodeInput {
  'area' : string,
  'cost' : number,
  'projectNumber' : string,
  'operation' : string,
  'csiCode' : string,
  'distribution' : string,
  'csiDivision' : string,
}
export interface CostCode__1 {
  'id' : CostCodeId,
  'area' : string,
  'cost' : number,
  'projectNumber' : string,
  'operation' : string,
  'csiCode' : string,
  'distribution' : string,
  'csiDivision' : string,
  'phaseId' : bigint,
}
export interface CreateScenarioRequest {
  'name' : string,
  'description' : string,
  'phaseOverrides' : Array<PhaseOverride>,
  'participantOverrides' : Array<ParticipantOverride>,
}
export interface CriticalChangePlanShared {
  'id' : string,
  'status' : CriticalPlanStatus,
  'phaseIds' : Array<string>,
  'responsibleParticipantIds' : Array<string>,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : string,
  'affectedStandardIds' : Array<string>,
  'hazardAnalysis' : string,
  'controlMeasures' : string,
  'csiCodes' : Array<string>,
}
export interface CriticalPathNode {
  'lateFinish' : number,
  'earlyFinish' : number,
  'isCritical' : boolean,
  'earlyStart' : number,
  'totalSlack' : number,
  'phaseName' : string,
  'phaseId' : string,
  'lateStart' : number,
}
export interface CriticalPlanApproval {
  'id' : string,
  'planId' : string,
  'approvedAt' : bigint,
  'approvedBy' : string,
  'role' : string,
  'approved' : boolean,
}
export type CriticalPlanStatus = { 'Approved' : null } |
  { 'Draft' : null } |
  { 'Rejected' : null } |
  { 'PendingApproval' : null };
export interface CumulativePoint {
  'crashedCash' : number,
  'phaseOrder' : bigint,
  'cumulativeSOV' : number,
  'cumulativeCash' : number,
  'phaseName' : string,
  'endOffset' : TimeOffset,
}
export interface CumulativePointWithCodes {
  'crashedCash' : number,
  'breakdown' : Array<CostCodeBreakdown>,
  'phaseOrder' : bigint,
  'cumulativeSOV' : number,
  'cumulativeCash' : number,
  'phaseName' : string,
  'endOffset' : TimeOffset,
}
export interface DefaultPhase {
  'durationDays' : bigint,
  'order' : bigint,
  'name' : string,
  'csiDivisions' : Array<bigint>,
}
export interface Drawing {
  'id' : string,
  'name' : string,
  'description' : string,
  'fileType' : DrawingFileType,
  'storageKey' : string,
  'category' : DrawingCategory,
  'uploadedAt' : bigint,
  'uploadedBy' : string,
}
export type DrawingCategory = { 'ArchitectDrawings' : null } |
  { 'ConstructionDrawings' : null } |
  { 'CADFiles' : null } |
  { 'Blueprints' : null } |
  { 'Photographs' : null } |
  { 'EngineeringDrawings' : null };
export type DrawingFileType = { 'DWG' : null } |
  { 'DXF' : null } |
  { 'JPG' : null } |
  { 'PDF' : null } |
  { 'PNG' : null };
export interface DrawingNotification {
  'id' : string,
  'drawingName' : string,
  'dismissed' : boolean,
  'requestedAt' : bigint,
  'requestedBy' : string,
  'drawingId' : string,
}
export interface EVMPoint {
  'cpi' : number,
  'spi' : number,
  'baselineType' : BaselineType,
  'phaseOrder' : bigint,
  'plannedValue' : number,
  'earnedValue' : number,
  'productivityIndex' : number,
  'actualCost' : number,
  'costVariance' : number,
  'customProductivityIndex' : [] | [number],
  'phaseName' : string,
  'scheduleVariance' : number,
  'phaseId' : bigint,
}
export interface FeatureLockSnapshot {
  'subscriptions' : boolean,
  'participants' : boolean,
  'documents' : boolean,
  'resources' : boolean,
  'scheduling' : boolean,
  'cost' : boolean,
  'compliance' : boolean,
  'oacMeetings' : boolean,
}
export type FormType = { 'MeetingMinutes' : null } |
  { 'G701' : null } |
  { 'G702' : null } |
  { 'G703' : null } |
  { 'Addendum' : null };
export type IdleTimeMode = { 'holdThroughProject' : null } |
  { 'releaseAtPhaseEnd' : null };
export interface IdleTimeSetting {
  'defaultIdleMode' : IdleTimeMode,
  'projectId' : string,
}
export interface MeetingPackage {
  'participants' : Array<string>,
  'date' : string,
  'link' : string,
  'time' : string,
}
export interface NCCERCertShared {
  'id' : string,
  'status' : NCCERCertStatus,
  'trade' : string,
  'expiresAt' : bigint,
  'discipline' : string,
  'level' : string,
  'state' : string,
  'participantId' : string,
  'certNumber' : string,
  'issuedAt' : bigint,
}
export type NCCERCertStatus = { 'Expiring' : null } |
  { 'Current' : null } |
  { 'Expired' : null };
export interface OACMeetingSession {
  'id' : string,
  'zoomMeetingId' : [] | [string],
  'sessionDate' : string,
  'linkedCategoryId' : [] | [string],
  'sessionTime' : string,
  'createdAt' : bigint,
  'projectId' : string,
  'zoomLink' : [] | [string],
}
export interface Participant {
  'id' : string,
  'status' : ParticipantStatus,
  'companyTrade' : string,
  'passcodeEmailSent' : boolean,
  'passcode' : [] | [string],
  'createdAt' : bigint,
  'role' : ParticipantRole,
  'fullName' : string,
  'email' : string,
  'notes' : string,
  'companyName' : string,
  'mobilePhone' : string,
  'officePhone' : string,
  'companyAddress' : string,
  'residentialAddress' : string,
}
export interface ParticipantAssignment {
  'costCodeId' : string,
  'variance' : [] | [number],
  'actualCost' : [] | [number],
  'rsMeansCrewRate' : [] | [number],
  'participantId' : string,
  'rsMeansMaterialRate' : [] | [number],
  'rsMeansEquipmentRate' : [] | [number],
  'rsMeansUnitCost' : [] | [number],
  'rsMeansSource' : RSMeansSource,
  'rsMeansLaborRate' : [] | [number],
  'phaseId' : string,
}
export interface ParticipantOverride {
  'participantId' : string,
  'costCodeAssignments' : Array<string>,
  'phaseAssignments' : Array<string>,
  'newRole' : [] | [string],
}
export type ParticipantRole = { 'EHSRepresentative' : null } |
  { 'Designer' : null } |
  { 'MechanicalEngineer' : null } |
  { 'Architect' : null } |
  { 'SpecialtyEngineer' : null } |
  { 'SafetyEngineer' : null } |
  { 'SafetyInspector' : null } |
  { 'CivilEngineer' : null } |
  { 'ConstructionManager' : null } |
  { 'Owner' : null } |
  { 'Contractor' : null };
export type ParticipantStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export interface PaymentMethodInfo {
  'expYear' : bigint,
  'paymentMethodId' : string,
  'last4' : string,
  'expMonth' : bigint,
  'isDefault' : boolean,
  'brand' : string,
}
export interface PayoutRecord {
  'status' : string,
  'date' : string,
  'amount' : number,
}
export interface Phase {
  'id' : PhaseId,
  'crashFactor' : number,
  'resourceMultiplier' : number,
  'name' : string,
  'costCodes' : Array<CostCode>,
  'phaseOrder' : bigint,
  'scheduleOfValues' : number,
  'requiredCash' : number,
  'endOffset' : TimeOffset,
  'startOffset' : TimeOffset,
}
export interface PhaseAllocation {
  'id' : string,
  'allocatedHours' : number,
  'resourceId' : string,
  'availableHours' : number,
  'manualLaborCost' : [] | [number],
  'actualHours' : [] | [number],
  'phaseId' : string,
  'laborCostSource' : string,
}
export interface PhaseAllocationInput {
  'allocatedHours' : number,
  'resourceId' : string,
  'availableHours' : number,
  'manualLaborCost' : [] | [number],
  'actualHours' : [] | [number],
  'phaseId' : string,
  'laborCostSource' : string,
}
export interface PhaseComplianceSummary {
  'total' : bigint,
  'compliant' : bigint,
  'signedOff' : boolean,
  'nonCompliant' : bigint,
  'notApplicable' : bigint,
  'phaseId' : string,
}
export type PhaseId = bigint;
export interface PhaseInput {
  'crashFactor' : [] | [number],
  'resourceMultiplier' : [] | [number],
  'name' : string,
  'costCodes' : [] | [Array<CostCodeInput>],
  'phaseOrder' : bigint,
  'scheduleOfValues' : number,
  'requiredCash' : number,
  'endOffset' : TimeOffset,
  'startOffset' : TimeOffset,
}
export interface PhaseOverride {
  'crashFactor' : number,
  'resourceMultiplier' : number,
  'laborCostOverride' : [] | [number],
  'phaseId' : string,
}
export interface PhaseSignOffShared {
  'id' : string,
  'role' : string,
  'signedAt' : bigint,
  'signedBy' : string,
  'approved' : boolean,
  'comments' : string,
  'phaseId' : string,
}
export interface PhaseStandardLink {
  'id' : string,
  'linkedAt' : bigint,
  'linkedBy' : string,
  'standardId' : string,
  'csiCode' : string,
  'phaseId' : string,
}
export interface ProjectCategory {
  'id' : string,
  'name' : string,
  'subtopics' : Array<ProjectSubtopic>,
}
export interface ProjectEVMSummary {
  'totalAC' : number,
  'totalCV' : number,
  'totalEV' : number,
  'totalPV' : number,
  'totalSV' : number,
  'projectPI' : number,
  'projectCPI' : number,
  'projectSPI' : number,
}
export interface ProjectSubtopic {
  'id' : string,
  'defaultCostCodeDivisions' : Array<bigint>,
  'name' : string,
  'defaultPhases' : Array<DefaultPhase>,
}
export interface RSMeansSettings {
  'apiKey' : [] | [string],
  'lastTestStatus' : [] | [string],
  'apiEnabled' : boolean,
}
export type RSMeansSource = { 'None' : null } |
  { 'ManualEntry' : null } |
  { 'LiveAPI' : null };
export interface ReminderState {
  'principal' : Principal,
  'day28EmailSent' : boolean,
  'day28Dismissed' : boolean,
  'day26EmailSent' : boolean,
  'day26Dismissed' : boolean,
}
export interface RenewalHistoryEntry {
  'id' : string,
  'status' : { 'Failed' : null } |
    { 'Paid' : null } |
    { 'Cancelled' : null } |
    { 'Pending' : null },
  'principal' : Principal,
  'monthlyCharge' : bigint,
  'endDate' : bigint,
  'createdAt' : bigint,
  'tier' : SubscriptionTier,
  'totalPaid' : bigint,
  'startDate' : bigint,
}
export interface Resource {
  'id' : string,
  'name' : string,
  'hourlyRate' : number,
  'idleTimeMode' : IdleTimeMode,
  'hourlyRateSource' : string,
  'resourceType' : ResourceType,
  'csiCode' : [] | [string],
  'crewSize' : [] | [bigint],
  'trackingLevel' : TrackingLevel,
}
export interface ResourceInput {
  'name' : string,
  'hourlyRate' : number,
  'idleTimeMode' : [] | [IdleTimeMode],
  'hourlyRateSource' : string,
  'resourceType' : ResourceType,
  'csiCode' : [] | [string],
  'crewSize' : [] | [bigint],
  'trackingLevel' : TrackingLevel,
}
export interface ResourceSummary {
  'resourceId' : string,
  'totalIdleHours' : number,
  'idleHoursCrashedBaseline' : number,
  'idleHoursOriginalBaseline' : number,
  'resourceName' : string,
  'totalLaborCost' : number,
  'totalAllocatedHours' : number,
  'trackingLevel' : TrackingLevel,
  'totalAvailableHours' : number,
}
export type ResourceType = { 'equipment' : null } |
  { 'labor' : null };
export type Result = { 'ok' : null } |
  { 'err' : string };
export type Result_1 = { 'ok' : UserSubscription } |
  { 'err' : string };
export type Result_2 = { 'ok' : CancellationRequest } |
  { 'err' : string };
export type Result_3 = { 'ok' : Array<string> } |
  { 'err' : string };
export type Result_4 = {
    'ok' : { 'name' : string, 'email' : string, 'phone' : string }
  } |
  { 'err' : string };
export type Result_5 = { 'ok' : string } |
  { 'err' : string };
export type Result_6 = { 'ok' : { 'name' : string, 'email' : string } } |
  { 'err' : string };
export interface ReviewRequest {
  'id' : string,
  'status' : string,
  'oacFormId' : [] | [string],
  'notes' : string,
  'requestedAt' : bigint,
  'requestedBy' : string,
  'drawingId' : string,
}
export interface SafetyStandard {
  'id' : string,
  'status' : StandardStatus,
  'title' : string,
  'code' : string,
  'csiDivisions' : Array<string>,
  'summary' : string,
  'state' : [] | [string],
  'relatedStandards' : Array<string>,
  'category' : StandardCategory,
  'applicableTrades' : Array<string>,
}
export interface Scenario {
  'id' : ScenarioId,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'updatedAt' : bigint,
  'phaseOverrides' : Array<PhaseOverride>,
  'participantOverrides' : Array<ParticipantOverride>,
}
export interface ScenarioBenchmarkVariance {
  'scenarioId' : ScenarioId,
  'divisionName' : string,
  'variance' : number,
  'actualCost' : number,
  'variancePct' : number,
  'divisionId' : bigint,
  'rsMeansCost' : number,
}
export interface ScenarioCashProjection {
  'cumulativePoints' : Array<[bigint, number]>,
  'scenarioId' : ScenarioId,
  'scenarioName' : string,
  'totalCost' : number,
}
export interface ScenarioEVMSummary {
  'cv' : number,
  'sv' : number,
  'cpi' : number,
  'spi' : number,
  'scenarioId' : ScenarioId,
  'plannedValue' : number,
  'earnedValue' : number,
  'actualCost' : number,
}
export type ScenarioId = string;
export interface ScenarioSummary {
  'id' : ScenarioId,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
}
export interface SessionSnapshot {
  'principal' : Principal,
  'lastActivity' : bigint,
  'isActive' : boolean,
  'timestamp' : bigint,
  'sessionId' : string,
  'userAgent' : string,
  'ipAddress' : string,
}
export interface ShareLink {
  'id' : string,
  'token' : string,
  'createdAt' : bigint,
  'isActive' : boolean,
  'projectId' : string,
}
export type StandardCategory = { 'IBC' : null } |
  { 'NCCER' : null } |
  { 'ANSI' : null } |
  { 'IEEE' : null } |
  { 'OSHA' : null };
export type StandardStatus = { 'Superseded' : null } |
  { 'Active' : null } |
  { 'Withdrawn' : null };
export type SubscriptionStatus = { 'trial' : null } |
  { 'active' : null } |
  { 'cancelled' : null } |
  { 'expired' : null } |
  { 'frozen' : null };
export type SubscriptionTier = { 'tier10year' : null } |
  { 'tier1year' : null } |
  { 'tier5year' : null };
export type TimeOffset = bigint;
export type TrackingLevel = { 'crew' : null } |
  { 'individual' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface TrialLink {
  'slug' : string,
  'tier' : SubscriptionTier,
  'isActive' : boolean,
}
export interface UserSubscription {
  'status' : SubscriptionStatus,
  'frozenReason' : [] | [string],
  'trialStartAt' : bigint,
  'frozenAt' : [] | [bigint],
  'stripeSubscriptionId' : [] | [string],
  'userId' : Principal,
  'subscriptionStartAt' : [] | [bigint],
  'tier' : SubscriptionTier,
  'cancelledAt' : [] | [bigint],
  'currentPlan' : SubscriptionTier,
  'stripeCustomerId' : [] | [string],
  'chargeScheduledAt' : bigint,
  'subscriptionExpiresAt' : [] | [bigint],
  'stripePaymentMethodId' : [] | [string],
}
export interface VerificationDocument {
  'documentType' : string,
  'stripeVerificationSessionId' : [] | [string],
  'storageKey' : string,
  'stripeVerificationStatus' : string,
  'adminReviewStatus' : string,
  'uploadedAt' : bigint,
}
export type ZoomMeetingResult = {
    'ok' : { 'joinUrl' : string, 'meetingId' : string }
  } |
  { 'err' : string };
export interface ZoomSettings {
  'clientId' : string,
  'fixedZoomLinks' : Array<[string, string]>,
  'clientSecret' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'activateSubscription' : ActorMethod<[string], Result_1>,
  'addDrawing' : ActorMethod<
    [string, DrawingCategory, DrawingFileType, string, string],
    Drawing
  >,
  'addLoginEmail' : ActorMethod<[string], Result>,
  'addNCCERCertification' : ActorMethod<
    [string, string, string, string, string, string, bigint, bigint],
    NCCERCertShared
  >,
  'addPaymentMethod' : ActorMethod<[string], Result_1>,
  'addRenewalHistoryEntry' : ActorMethod<[RenewalHistoryEntry], Result>,
  'addUserLoginEmail' : ActorMethod<[string, string], Result>,
  'applyProjectTemplate' : ActorMethod<[string, string], ApplyTemplateResult>,
  'approveCancellationRequest' : ActorMethod<[string], Result>,
  'approveCriticalChangePlan' : ActorMethod<
    [string, boolean],
    CriticalPlanApproval
  >,
  'approveDocumentReview' : ActorMethod<[Principal, string], Result>,
  'approveParticipant' : ActorMethod<[string], [] | [Participant]>,
  'assignAdmin' : ActorMethod<[Principal], Result>,
  'assignParticipantToPhaseCode' : ActorMethod<
    [ParticipantAssignment],
    ParticipantAssignment
  >,
  'autoLinkStandardsForCategory' : ActorMethod<
    [string, string, [] | [string]],
    Array<string>
  >,
  'canAccessCompliance' : ActorMethod<[ParticipantRole], boolean>,
  'canManageCriticalPlans' : ActorMethod<[ParticipantRole], boolean>,
  'cancelTrial' : ActorMethod<[], Result>,
  'changeControllerPassword' : ActorMethod<[string], Result>,
  'changePassword' : ActorMethod<[string, string, string], Result>,
  /**
   * / One-time claim: the first caller who finds _controller == anonymous
   * / principal becomes the permanent controller.  Secure because the
   * / deployer is the only one who can call this before any user interaction.
   */
  'claimController' : ActorMethod<[], Result>,
  'compareScenarios' : ActorMethod<
    [Array<string>],
    Array<ScenarioCashProjection>
  >,
  'computeCriticalPath' : ActorMethod<
    [Array<CPMPhaseInput>],
    Array<CriticalPathNode>
  >,
  'computeResourceSummaries' : ActorMethod<
    [number, number],
    Array<ResourceSummary>
  >,
  'createCriticalChangePlan' : ActorMethod<
    [
      string,
      Array<string>,
      Array<string>,
      string,
      string,
      Array<string>,
      Array<string>,
    ],
    CriticalChangePlanShared
  >,
  'createOACSession' : ActorMethod<[string, string], string>,
  'createParticipant' : ActorMethod<[Participant], Participant>,
  'createReviewRequest' : ActorMethod<
    [string, string],
    [] | [[ReviewRequest, DrawingNotification]]
  >,
  'createScenario' : ActorMethod<
    [CreateScenarioRequest],
    { 'ok' : Scenario } |
      { 'err' : string }
  >,
  'deactivateShareLink' : ActorMethod<[string], boolean>,
  'deleteCostCode' : ActorMethod<
    [bigint, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteDrawing' : ActorMethod<[string], boolean>,
  'deleteParticipant' : ActorMethod<[string], boolean>,
  'deletePhase' : ActorMethod<[bigint], boolean>,
  'deletePhaseAllocation' : ActorMethod<[string], boolean>,
  'deleteResource' : ActorMethod<[string], boolean>,
  'deleteReviewRequest' : ActorMethod<[string], boolean>,
  'deleteScenario' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'denyCancellationRequest' : ActorMethod<[string], Result>,
  'directCancelSubscription' : ActorMethod<[Principal], Result>,
  'dismissDrawingNotification' : ActorMethod<[string], boolean>,
  'dismissReminder' : ActorMethod<[bigint], undefined>,
  'emailLogin' : ActorMethod<[string, string, string, string], Result_6>,
  'emailOnlyLogin' : ActorMethod<[string], Result_5>,
  'endSession' : ActorMethod<[string], undefined>,
  'enrollTrial' : ActorMethod<[SubscriptionTier, string, string], Result_1>,
  'expireSubscription' : ActorMethod<[], Result>,
  'fetchRSMeansBenchmarks' : ActorMethod<[string], string>,
  'freezeSubscription' : ActorMethod<[Principal, string], Result>,
  'generateResetCode' : ActorMethod<[string], Result_5>,
  'generateShareLink' : ActorMethod<[string], ShareLink>,
  'generateUserResetCode' : ActorMethod<[string], Result_5>,
  'generateZoomMeeting' : ActorMethod<[string, string], ZoomMeetingResult>,
  'getAIAForm' : ActorMethod<[string], [] | [AIAFormEntry]>,
  'getAIAForms' : ActorMethod<[string], Array<AIAFormEntry>>,
  'getActiveFilter' : ActorMethod<[], [[] | [string], [] | [string]]>,
  'getActiveSessions' : ActorMethod<[], Array<SessionSnapshot>>,
  'getAdminList' : ActorMethod<[], Array<AdminRole>>,
  'getAllCancellationRequests' : ActorMethod<[], Array<CancellationRequest>>,
  'getAllUsers' : ActorMethod<
    [],
    Array<
      {
        'name' : string,
        'createdAt' : bigint,
        'email' : string,
        'lastLogin' : bigint,
      }
    >
  >,
  'getAppSettings' : ActorMethod<[], AppSettings>,
  'getBankAccount' : ActorMethod<[], [] | [BankAccount]>,
  'getCertificationsForPhase' : ActorMethod<[string], Array<NCCERCertShared>>,
  'getComplianceItemsForPhase' : ActorMethod<
    [string],
    Array<ComplianceItemShared>
  >,
  'getControllerProfile' : ActorMethod<[], Result_4>,
  'getCostCodeCompletion' : ActorMethod<[bigint, bigint], [] | [number]>,
  'getCostCodesForPhase' : ActorMethod<
    [bigint],
    { 'ok' : Array<CostCode__1> } |
      { 'err' : string }
  >,
  'getCriticalChangePlansForPhase' : ActorMethod<
    [string],
    Array<CriticalChangePlanShared>
  >,
  'getCumulativeCashRequirement' : ActorMethod<[], Array<CumulativePoint>>,
  'getCumulativeCrashedRequirement' : ActorMethod<[], Array<CumulativePoint>>,
  'getCumulativeWithBreakdown' : ActorMethod<
    [],
    Array<CumulativePointWithCodes>
  >,
  'getDocumentReviewStatus' : ActorMethod<[], Array<VerificationDocument>>,
  'getDrawingNotifications' : ActorMethod<[], Array<DrawingNotification>>,
  'getDrawings' : ActorMethod<[], Array<Drawing>>,
  'getEarnedValueMetrics' : ActorMethod<[BaselineType], Array<EVMPoint>>,
  'getFeatureLocks' : ActorMethod<[], FeatureLockSnapshot>,
  'getFilteredStandards' : ActorMethod<
    [string, string, [] | [string]],
    Array<SafetyStandard>
  >,
  'getIdleTimeSetting' : ActorMethod<[], [] | [IdleTimeSetting]>,
  'getLoginEmails' : ActorMethod<[], Result_3>,
  'getLoginHistory' : ActorMethod<[], Array<SessionSnapshot>>,
  'getNCCERCertificationsForParticipant' : ActorMethod<
    [string],
    Array<NCCERCertShared>
  >,
  'getNextPayoutDate' : ActorMethod<[], [] | [string]>,
  'getOACSession' : ActorMethod<[string], [] | [OACMeetingSession]>,
  'getOACSessions' : ActorMethod<[], Array<OACMeetingSession>>,
  'getParticipant' : ActorMethod<[string], [] | [Participant]>,
  'getParticipantAssignments' : ActorMethod<
    [string],
    Array<ParticipantAssignment>
  >,
  'getParticipantMeetingPackage' : ActorMethod<[string], MeetingPackage>,
  'getParticipants' : ActorMethod<[], Array<Participant>>,
  'getPaymentMethods' : ActorMethod<[], Array<PaymentMethodInfo>>,
  'getPayoutRecords' : ActorMethod<[], Array<PayoutRecord>>,
  'getPhaseAllocations' : ActorMethod<[], Array<PhaseAllocation>>,
  'getPhaseAllocationsByPhase' : ActorMethod<[string], Array<PhaseAllocation>>,
  'getPhaseAllocationsByResource' : ActorMethod<
    [string],
    Array<PhaseAllocation>
  >,
  'getPhaseComplianceStatus' : ActorMethod<[string], PhaseComplianceSummary>,
  'getPhases' : ActorMethod<[], Array<Phase>>,
  'getProjectCategories' : ActorMethod<[], Array<ProjectCategory>>,
  'getProjectEVMSummary' : ActorMethod<[BaselineType], ProjectEVMSummary>,
  'getProjectShareLinks' : ActorMethod<[string], Array<ShareLink>>,
  'getProjectSubtopic' : ActorMethod<[string, string], [] | [ProjectSubtopic]>,
  'getRSMeansSettings' : ActorMethod<[], RSMeansSettings>,
  'getReminderState' : ActorMethod<[], [] | [ReminderState]>,
  'getRenewalHistory' : ActorMethod<[], Array<RenewalHistoryEntry>>,
  'getResources' : ActorMethod<[], Array<Resource>>,
  'getResourcesByType' : ActorMethod<[ResourceType], Array<Resource>>,
  'getReviewRequests' : ActorMethod<[], Array<ReviewRequest>>,
  'getScenario' : ActorMethod<[string], [] | [Scenario]>,
  'getScenarioBenchmarkVariances' : ActorMethod<
    [string],
    Array<ScenarioBenchmarkVariance>
  >,
  'getScenarioCashProjection' : ActorMethod<
    [string],
    [] | [ScenarioCashProjection]
  >,
  'getScenarioEVMSummary' : ActorMethod<[string], [] | [ScenarioEVMSummary]>,
  'getShareLink' : ActorMethod<[string], [] | [ShareLink]>,
  'getSignOffsForPhase' : ActorMethod<[string], Array<PhaseSignOffShared>>,
  'getStandard' : ActorMethod<[string], [] | [SafetyStandard]>,
  'getStandardsForCsiCode' : ActorMethod<[string], Array<SafetyStandard>>,
  'getStandardsForPhase' : ActorMethod<[string], Array<SafetyStandard>>,
  'getSubscriptionStatus' : ActorMethod<[], SubscriptionStatus>,
  'getTrialLinks' : ActorMethod<[], Array<TrialLink>>,
  'getUserCancellationRequests' : ActorMethod<
    [string],
    Array<CancellationRequest>
  >,
  'getUserLoginEmails' : ActorMethod<[string], Array<string>>,
  'getUserSubscription' : ActorMethod<[], [] | [UserSubscription]>,
  'getZoomSettings' : ActorMethod<[], [] | [ZoomSettings]>,
  'isAdmin' : ActorMethod<[Principal], boolean>,
  'isController' : ActorMethod<[Principal], boolean>,
  'isPhaseSignedOff' : ActorMethod<[string], boolean>,
  'isPlanFullyApproved' : ActorMethod<[string], boolean>,
  'linkStandardToPhase' : ActorMethod<
    [string, string, string],
    PhaseStandardLink
  >,
  'listScenarios' : ActorMethod<[], Array<ScenarioSummary>>,
  'registerEmailUser' : ActorMethod<[string, string, string, string], Result>,
  'rejectParticipant' : ActorMethod<[string], [] | [Participant]>,
  'removeLoginEmail' : ActorMethod<[string], Result>,
  'removeParticipantAssignment' : ActorMethod<
    [string, string, string],
    boolean
  >,
  'removeUserLoginEmail' : ActorMethod<[string], Result>,
  'renewSubscription' : ActorMethod<[], Result_1>,
  'resendPasscode' : ActorMethod<[string], boolean>,
  'revokeAdmin' : ActorMethod<[Principal], Result>,
  'saveAIAForm' : ActorMethod<
    [string, FormType, Array<[string, string]>, string],
    string
  >,
  'saveAppSettings' : ActorMethod<[AppSettings], AppSettings>,
  'saveBankAccount' : ActorMethod<[string, string, string], undefined>,
  'savePayoutRecords' : ActorMethod<[Array<PayoutRecord>], undefined>,
  'saveRSMeansSettings' : ActorMethod<[RSMeansSettings], RSMeansSettings>,
  'saveZoomSettings' : ActorMethod<[ZoomSettings], boolean>,
  'searchStandards' : ActorMethod<
    [string, [] | [StandardCategory], [] | [string]],
    Array<SafetyStandard>
  >,
  'setActiveFilter' : ActorMethod<[[] | [string], [] | [string]], undefined>,
  'setFeatureLock' : ActorMethod<
    [string, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setFixedZoomLink' : ActorMethod<[string, string], boolean>,
  'setIdleTimeSetting' : ActorMethod<[IdleTimeMode], IdleTimeSetting>,
  'setNextPayoutDate' : ActorMethod<[string], undefined>,
  'setPhases' : ActorMethod<[Array<PhaseInput>], undefined>,
  'setReminderEmailSent' : ActorMethod<[bigint], undefined>,
  'setStripeSecretKey' : ActorMethod<[string], undefined>,
  'submitCancellationRequest' : ActorMethod<[string, string], Result_2>,
  'submitDocumentForReview' : ActorMethod<
    [string, string, [] | [string]],
    VerificationDocument
  >,
  'submitPhaseSignOff' : ActorMethod<
    [string, boolean, string],
    PhaseSignOffShared
  >,
  'submitPlanForApproval' : ActorMethod<
    [string],
    [] | [CriticalChangePlanShared]
  >,
  'switchTrialTier' : ActorMethod<[SubscriptionTier], Result_1>,
  'testRSMeansConnection' : ActorMethod<[], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unfreezeSubscription' : ActorMethod<[Principal], Result>,
  'unlinkStandardFromPhase' : ActorMethod<[string, string, string], boolean>,
  'updateAIAForm' : ActorMethod<[string, Array<[string, string]>], boolean>,
  'updateControllerProfile' : ActorMethod<[string, string, string], Result>,
  'updateCostCodeCompletion' : ActorMethod<[bigint, bigint, number], undefined>,
  'updateCriticalChangePlan' : ActorMethod<
    [
      string,
      [] | [string],
      [] | [Array<string>],
      [] | [Array<string>],
      [] | [string],
      [] | [string],
      [] | [Array<string>],
      [] | [Array<string>],
    ],
    [] | [CriticalChangePlanShared]
  >,
  'updateNCCERCertification' : ActorMethod<
    [
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [bigint],
      [] | [bigint],
      [] | [NCCERCertStatus],
    ],
    [] | [NCCERCertShared]
  >,
  'updateOACSessionZoomLink' : ActorMethod<[string, string, string], boolean>,
  'updateParticipant' : ActorMethod<[Participant], [] | [Participant]>,
  'updateRSMeansEntry' : ActorMethod<
    [string, string, string, ParticipantAssignment],
    [] | [ParticipantAssignment]
  >,
  'updateReviewRequest' : ActorMethod<
    [string, string, string],
    [] | [ReviewRequest]
  >,
  'updateScenario' : ActorMethod<
    [string, CreateScenarioRequest],
    { 'ok' : Scenario } |
      { 'err' : string }
  >,
  'upsertComplianceItem' : ActorMethod<
    [string, string, ComplianceStatus, ComplianceSeverity, string],
    ComplianceItemShared
  >,
  'upsertCostCode' : ActorMethod<
    [bigint, CostCodeInput],
    { 'ok' : CostCode__1 } |
      { 'err' : string }
  >,
  'upsertPhase' : ActorMethod<[bigint, PhaseInput], Phase>,
  'upsertPhaseAllocation' : ActorMethod<
    [PhaseAllocationInput],
    PhaseAllocation
  >,
  'upsertResource' : ActorMethod<[ResourceInput], Resource>,
  'validateResetCode' : ActorMethod<[string, string, string], Result>,
  'zoomTransform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];