/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SubscriptionStatus = IDL.Variant({
  'trial' : IDL.Null,
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'expired' : IDL.Null,
  'frozen' : IDL.Null,
});
export const SubscriptionTier = IDL.Variant({
  'tier10year' : IDL.Null,
  'tier1year' : IDL.Null,
  'tier5year' : IDL.Null,
});
export const UserSubscription = IDL.Record({
  'status' : SubscriptionStatus,
  'frozenReason' : IDL.Opt(IDL.Text),
  'trialStartAt' : IDL.Int,
  'frozenAt' : IDL.Opt(IDL.Int),
  'stripeSubscriptionId' : IDL.Opt(IDL.Text),
  'userId' : IDL.Principal,
  'subscriptionStartAt' : IDL.Opt(IDL.Int),
  'tier' : SubscriptionTier,
  'cancelledAt' : IDL.Opt(IDL.Int),
  'currentPlan' : SubscriptionTier,
  'stripeCustomerId' : IDL.Opt(IDL.Text),
  'chargeScheduledAt' : IDL.Int,
  'subscriptionExpiresAt' : IDL.Opt(IDL.Int),
  'stripePaymentMethodId' : IDL.Opt(IDL.Text),
});
export const Result_1 = IDL.Variant({
  'ok' : UserSubscription,
  'err' : IDL.Text,
});
export const DrawingCategory = IDL.Variant({
  'ArchitectDrawings' : IDL.Null,
  'ConstructionDrawings' : IDL.Null,
  'CADFiles' : IDL.Null,
  'Blueprints' : IDL.Null,
  'Photographs' : IDL.Null,
  'EngineeringDrawings' : IDL.Null,
});
export const DrawingFileType = IDL.Variant({
  'DWG' : IDL.Null,
  'DXF' : IDL.Null,
  'JPG' : IDL.Null,
  'PDF' : IDL.Null,
  'PNG' : IDL.Null,
});
export const Drawing = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'fileType' : DrawingFileType,
  'storageKey' : IDL.Text,
  'category' : DrawingCategory,
  'uploadedAt' : IDL.Int,
  'uploadedBy' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const NCCERCertStatus = IDL.Variant({
  'Expiring' : IDL.Null,
  'Current' : IDL.Null,
  'Expired' : IDL.Null,
});
export const NCCERCertShared = IDL.Record({
  'id' : IDL.Text,
  'status' : NCCERCertStatus,
  'trade' : IDL.Text,
  'expiresAt' : IDL.Int,
  'discipline' : IDL.Text,
  'level' : IDL.Text,
  'state' : IDL.Text,
  'participantId' : IDL.Text,
  'certNumber' : IDL.Text,
  'issuedAt' : IDL.Int,
});
export const RenewalHistoryEntry = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'Failed' : IDL.Null,
    'Paid' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Pending' : IDL.Null,
  }),
  'principal' : IDL.Principal,
  'monthlyCharge' : IDL.Nat,
  'endDate' : IDL.Int,
  'createdAt' : IDL.Int,
  'tier' : SubscriptionTier,
  'totalPaid' : IDL.Nat,
  'startDate' : IDL.Int,
});
export const ApplyTemplateResult = IDL.Variant({
  'ok' : IDL.Record({ 'phasesCreated' : IDL.Nat }),
  'err' : IDL.Text,
});
export const CriticalPlanApproval = IDL.Record({
  'id' : IDL.Text,
  'planId' : IDL.Text,
  'approvedAt' : IDL.Int,
  'approvedBy' : IDL.Text,
  'role' : IDL.Text,
  'approved' : IDL.Bool,
});
export const ParticipantStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const ParticipantRole = IDL.Variant({
  'EHSRepresentative' : IDL.Null,
  'Designer' : IDL.Null,
  'MechanicalEngineer' : IDL.Null,
  'Architect' : IDL.Null,
  'SpecialtyEngineer' : IDL.Null,
  'SafetyEngineer' : IDL.Null,
  'SafetyInspector' : IDL.Null,
  'CivilEngineer' : IDL.Null,
  'ConstructionManager' : IDL.Null,
  'Owner' : IDL.Null,
  'Contractor' : IDL.Null,
});
export const Participant = IDL.Record({
  'id' : IDL.Text,
  'status' : ParticipantStatus,
  'companyTrade' : IDL.Text,
  'passcodeEmailSent' : IDL.Bool,
  'passcode' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'role' : ParticipantRole,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'notes' : IDL.Text,
  'companyName' : IDL.Text,
  'mobilePhone' : IDL.Text,
  'officePhone' : IDL.Text,
  'companyAddress' : IDL.Text,
  'residentialAddress' : IDL.Text,
});
export const RSMeansSource = IDL.Variant({
  'None' : IDL.Null,
  'ManualEntry' : IDL.Null,
  'LiveAPI' : IDL.Null,
});
export const ParticipantAssignment = IDL.Record({
  'costCodeId' : IDL.Text,
  'variance' : IDL.Opt(IDL.Float64),
  'actualCost' : IDL.Opt(IDL.Float64),
  'rsMeansCrewRate' : IDL.Opt(IDL.Float64),
  'participantId' : IDL.Text,
  'rsMeansMaterialRate' : IDL.Opt(IDL.Float64),
  'rsMeansEquipmentRate' : IDL.Opt(IDL.Float64),
  'rsMeansUnitCost' : IDL.Opt(IDL.Float64),
  'rsMeansSource' : RSMeansSource,
  'rsMeansLaborRate' : IDL.Opt(IDL.Float64),
  'phaseId' : IDL.Text,
});
export const ScenarioId = IDL.Text;
export const ScenarioCashProjection = IDL.Record({
  'cumulativePoints' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Float64)),
  'scenarioId' : ScenarioId,
  'scenarioName' : IDL.Text,
  'totalCost' : IDL.Float64,
});
export const CPMPhaseInput = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'endOffset' : IDL.Float64,
  'dependencies' : IDL.Vec(IDL.Text),
  'startOffset' : IDL.Float64,
});
export const CriticalPathNode = IDL.Record({
  'lateFinish' : IDL.Float64,
  'earlyFinish' : IDL.Float64,
  'isCritical' : IDL.Bool,
  'earlyStart' : IDL.Float64,
  'totalSlack' : IDL.Float64,
  'phaseName' : IDL.Text,
  'phaseId' : IDL.Text,
  'lateStart' : IDL.Float64,
});
export const TrackingLevel = IDL.Variant({
  'crew' : IDL.Null,
  'individual' : IDL.Null,
});
export const ResourceSummary = IDL.Record({
  'resourceId' : IDL.Text,
  'totalIdleHours' : IDL.Float64,
  'idleHoursCrashedBaseline' : IDL.Float64,
  'idleHoursOriginalBaseline' : IDL.Float64,
  'resourceName' : IDL.Text,
  'totalLaborCost' : IDL.Float64,
  'totalAllocatedHours' : IDL.Float64,
  'trackingLevel' : TrackingLevel,
  'totalAvailableHours' : IDL.Float64,
});
export const CriticalPlanStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Draft' : IDL.Null,
  'Rejected' : IDL.Null,
  'PendingApproval' : IDL.Null,
});
export const CriticalChangePlanShared = IDL.Record({
  'id' : IDL.Text,
  'status' : CriticalPlanStatus,
  'phaseIds' : IDL.Vec(IDL.Text),
  'responsibleParticipantIds' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Text,
  'affectedStandardIds' : IDL.Vec(IDL.Text),
  'hazardAnalysis' : IDL.Text,
  'controlMeasures' : IDL.Text,
  'csiCodes' : IDL.Vec(IDL.Text),
});
export const ReviewRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'oacFormId' : IDL.Opt(IDL.Text),
  'notes' : IDL.Text,
  'requestedAt' : IDL.Int,
  'requestedBy' : IDL.Text,
  'drawingId' : IDL.Text,
});
export const DrawingNotification = IDL.Record({
  'id' : IDL.Text,
  'drawingName' : IDL.Text,
  'dismissed' : IDL.Bool,
  'requestedAt' : IDL.Int,
  'requestedBy' : IDL.Text,
  'drawingId' : IDL.Text,
});
export const PhaseOverride = IDL.Record({
  'crashFactor' : IDL.Float64,
  'resourceMultiplier' : IDL.Float64,
  'laborCostOverride' : IDL.Opt(IDL.Float64),
  'phaseId' : IDL.Text,
});
export const ParticipantOverride = IDL.Record({
  'participantId' : IDL.Text,
  'costCodeAssignments' : IDL.Vec(IDL.Text),
  'phaseAssignments' : IDL.Vec(IDL.Text),
  'newRole' : IDL.Opt(IDL.Text),
});
export const CreateScenarioRequest = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'phaseOverrides' : IDL.Vec(PhaseOverride),
  'participantOverrides' : IDL.Vec(ParticipantOverride),
});
export const Scenario = IDL.Record({
  'id' : ScenarioId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'phaseOverrides' : IDL.Vec(PhaseOverride),
  'participantOverrides' : IDL.Vec(ParticipantOverride),
});
export const Result_6 = IDL.Variant({
  'ok' : IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text }),
  'err' : IDL.Text,
});
export const Result_5 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const ShareLink = IDL.Record({
  'id' : IDL.Text,
  'token' : IDL.Text,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'projectId' : IDL.Text,
});
export const ZoomMeetingResult = IDL.Variant({
  'ok' : IDL.Record({ 'joinUrl' : IDL.Text, 'meetingId' : IDL.Text }),
  'err' : IDL.Text,
});
export const FormType = IDL.Variant({
  'MeetingMinutes' : IDL.Null,
  'G701' : IDL.Null,
  'G702' : IDL.Null,
  'G703' : IDL.Null,
  'Addendum' : IDL.Null,
});
export const AIAFormEntry = IDL.Record({
  'id' : IDL.Text,
  'submittedByRole' : IDL.Text,
  'submittedAt' : IDL.Int,
  'formType' : FormType,
  'lastModified' : IDL.Int,
  'sessionId' : IDL.Text,
  'fieldData' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
});
export const SessionSnapshot = IDL.Record({
  'principal' : IDL.Principal,
  'lastActivity' : IDL.Int,
  'isActive' : IDL.Bool,
  'timestamp' : IDL.Int,
  'sessionId' : IDL.Text,
  'userAgent' : IDL.Text,
  'ipAddress' : IDL.Text,
});
export const AdminRole = IDL.Record({
  'assignedAt' : IDL.Int,
  'assignedBy' : IDL.Principal,
  'assignedPrincipal' : IDL.Principal,
});
export const CancellationRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'denied' : IDL.Null,
  'approved' : IDL.Null,
});
export const CancellationRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : CancellationRequestStatus,
  'email' : IDL.Text,
  'subscriberPrincipal' : IDL.Principal,
  'requestedAt' : IDL.Int,
  'reason' : IDL.Text,
});
export const RSMeansSettings = IDL.Record({
  'apiKey' : IDL.Opt(IDL.Text),
  'lastTestStatus' : IDL.Opt(IDL.Text),
  'apiEnabled' : IDL.Bool,
});
export const AccessControlMode = IDL.Variant({
  'RoleGated' : IDL.Null,
  'ProjectManagerOnly' : IDL.Null,
});
export const AppSettings = IDL.Record({
  'activeCategoryId' : IDL.Opt(IDL.Text),
  'projectManagerId' : IDL.Opt(IDL.Text),
  'rsMeansSettings' : RSMeansSettings,
  'activeSubtopicId' : IDL.Opt(IDL.Text),
  'accessControlMode' : AccessControlMode,
});
export const BankAccount = IDL.Record({
  'nextPayoutDate' : IDL.Opt(IDL.Text),
  'routingNumber' : IDL.Text,
  'accountHolderName' : IDL.Text,
  'connectedToStripe' : IDL.Bool,
  'isVerified' : IDL.Bool,
  'accountNumberLast4' : IDL.Text,
});
export const ComplianceStatus = IDL.Variant({
  'NA' : IDL.Null,
  'NonCompliant' : IDL.Null,
  'Compliant' : IDL.Null,
});
export const ComplianceSeverity = IDL.Variant({
  'None' : IDL.Null,
  'Critical' : IDL.Null,
  'Major' : IDL.Null,
  'Minor' : IDL.Null,
});
export const ComplianceItemShared = IDL.Record({
  'id' : IDL.Text,
  'status' : ComplianceStatus,
  'notes' : IDL.Text,
  'standardId' : IDL.Text,
  'checkedAt' : IDL.Int,
  'checkedBy' : IDL.Text,
  'severity' : ComplianceSeverity,
  'phaseId' : IDL.Text,
});
export const Result_4 = IDL.Variant({
  'ok' : IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  }),
  'err' : IDL.Text,
});
export const CostCodeId = IDL.Nat;
export const CostCode__1 = IDL.Record({
  'id' : CostCodeId,
  'area' : IDL.Text,
  'cost' : IDL.Float64,
  'projectNumber' : IDL.Text,
  'operation' : IDL.Text,
  'csiCode' : IDL.Text,
  'distribution' : IDL.Text,
  'csiDivision' : IDL.Text,
  'phaseId' : IDL.Nat,
});
export const TimeOffset = IDL.Int;
export const CumulativePoint = IDL.Record({
  'crashedCash' : IDL.Float64,
  'phaseOrder' : IDL.Nat,
  'cumulativeSOV' : IDL.Float64,
  'cumulativeCash' : IDL.Float64,
  'phaseName' : IDL.Text,
  'endOffset' : TimeOffset,
});
export const CostCodeBreakdown = IDL.Record({
  'cumulativeCost' : IDL.Float64,
  'csiCode' : IDL.Text,
  'csiDivision' : IDL.Text,
});
export const CumulativePointWithCodes = IDL.Record({
  'crashedCash' : IDL.Float64,
  'breakdown' : IDL.Vec(CostCodeBreakdown),
  'phaseOrder' : IDL.Nat,
  'cumulativeSOV' : IDL.Float64,
  'cumulativeCash' : IDL.Float64,
  'phaseName' : IDL.Text,
  'endOffset' : TimeOffset,
});
export const VerificationDocument = IDL.Record({
  'documentType' : IDL.Text,
  'stripeVerificationSessionId' : IDL.Opt(IDL.Text),
  'storageKey' : IDL.Text,
  'stripeVerificationStatus' : IDL.Text,
  'adminReviewStatus' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const BaselineType = IDL.Variant({
  'crashed' : IDL.Null,
  'original' : IDL.Null,
});
export const EVMPoint = IDL.Record({
  'cpi' : IDL.Float64,
  'spi' : IDL.Float64,
  'baselineType' : BaselineType,
  'phaseOrder' : IDL.Nat,
  'plannedValue' : IDL.Float64,
  'earnedValue' : IDL.Float64,
  'productivityIndex' : IDL.Float64,
  'actualCost' : IDL.Float64,
  'costVariance' : IDL.Float64,
  'customProductivityIndex' : IDL.Opt(IDL.Float64),
  'phaseName' : IDL.Text,
  'scheduleVariance' : IDL.Float64,
  'phaseId' : IDL.Nat,
});
export const FeatureLockSnapshot = IDL.Record({
  'subscriptions' : IDL.Bool,
  'participants' : IDL.Bool,
  'documents' : IDL.Bool,
  'resources' : IDL.Bool,
  'scheduling' : IDL.Bool,
  'cost' : IDL.Bool,
  'compliance' : IDL.Bool,
  'oacMeetings' : IDL.Bool,
});
export const StandardStatus = IDL.Variant({
  'Superseded' : IDL.Null,
  'Active' : IDL.Null,
  'Withdrawn' : IDL.Null,
});
export const StandardCategory = IDL.Variant({
  'IBC' : IDL.Null,
  'NCCER' : IDL.Null,
  'ANSI' : IDL.Null,
  'IEEE' : IDL.Null,
  'OSHA' : IDL.Null,
});
export const SafetyStandard = IDL.Record({
  'id' : IDL.Text,
  'status' : StandardStatus,
  'title' : IDL.Text,
  'code' : IDL.Text,
  'csiDivisions' : IDL.Vec(IDL.Text),
  'summary' : IDL.Text,
  'state' : IDL.Opt(IDL.Text),
  'relatedStandards' : IDL.Vec(IDL.Text),
  'category' : StandardCategory,
  'applicableTrades' : IDL.Vec(IDL.Text),
});
export const IdleTimeMode = IDL.Variant({
  'holdThroughProject' : IDL.Null,
  'releaseAtPhaseEnd' : IDL.Null,
});
export const IdleTimeSetting = IDL.Record({
  'defaultIdleMode' : IdleTimeMode,
  'projectId' : IDL.Text,
});
export const Result_3 = IDL.Variant({
  'ok' : IDL.Vec(IDL.Text),
  'err' : IDL.Text,
});
export const OACMeetingSession = IDL.Record({
  'id' : IDL.Text,
  'zoomMeetingId' : IDL.Opt(IDL.Text),
  'sessionDate' : IDL.Text,
  'linkedCategoryId' : IDL.Opt(IDL.Text),
  'sessionTime' : IDL.Text,
  'createdAt' : IDL.Int,
  'projectId' : IDL.Text,
  'zoomLink' : IDL.Opt(IDL.Text),
});
export const MeetingPackage = IDL.Record({
  'participants' : IDL.Vec(IDL.Text),
  'date' : IDL.Text,
  'link' : IDL.Text,
  'time' : IDL.Text,
});
export const PaymentMethodInfo = IDL.Record({
  'expYear' : IDL.Nat,
  'paymentMethodId' : IDL.Text,
  'last4' : IDL.Text,
  'expMonth' : IDL.Nat,
  'isDefault' : IDL.Bool,
  'brand' : IDL.Text,
});
export const PayoutRecord = IDL.Record({
  'status' : IDL.Text,
  'date' : IDL.Text,
  'amount' : IDL.Float64,
});
export const PhaseAllocation = IDL.Record({
  'id' : IDL.Text,
  'allocatedHours' : IDL.Float64,
  'resourceId' : IDL.Text,
  'availableHours' : IDL.Float64,
  'manualLaborCost' : IDL.Opt(IDL.Float64),
  'actualHours' : IDL.Opt(IDL.Float64),
  'phaseId' : IDL.Text,
  'laborCostSource' : IDL.Text,
});
export const PhaseComplianceSummary = IDL.Record({
  'total' : IDL.Nat,
  'compliant' : IDL.Nat,
  'signedOff' : IDL.Bool,
  'nonCompliant' : IDL.Nat,
  'notApplicable' : IDL.Nat,
  'phaseId' : IDL.Text,
});
export const PhaseId = IDL.Nat;
export const CostCode = IDL.Record({
  'id' : IDL.Nat,
  'area' : IDL.Text,
  'cost' : IDL.Float64,
  'projectNumber' : IDL.Text,
  'operation' : IDL.Text,
  'csiCode' : IDL.Text,
  'distribution' : IDL.Text,
  'csiDivision' : IDL.Text,
  'phaseId' : IDL.Nat,
});
export const Phase = IDL.Record({
  'id' : PhaseId,
  'crashFactor' : IDL.Float64,
  'resourceMultiplier' : IDL.Float64,
  'name' : IDL.Text,
  'costCodes' : IDL.Vec(CostCode),
  'phaseOrder' : IDL.Nat,
  'scheduleOfValues' : IDL.Float64,
  'requiredCash' : IDL.Float64,
  'endOffset' : TimeOffset,
  'startOffset' : TimeOffset,
});
export const DefaultPhase = IDL.Record({
  'durationDays' : IDL.Nat,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'csiDivisions' : IDL.Vec(IDL.Nat),
});
export const ProjectSubtopic = IDL.Record({
  'id' : IDL.Text,
  'defaultCostCodeDivisions' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
  'defaultPhases' : IDL.Vec(DefaultPhase),
});
export const ProjectCategory = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'subtopics' : IDL.Vec(ProjectSubtopic),
});
export const ProjectEVMSummary = IDL.Record({
  'totalAC' : IDL.Float64,
  'totalCV' : IDL.Float64,
  'totalEV' : IDL.Float64,
  'totalPV' : IDL.Float64,
  'totalSV' : IDL.Float64,
  'projectPI' : IDL.Float64,
  'projectCPI' : IDL.Float64,
  'projectSPI' : IDL.Float64,
});
export const ReminderState = IDL.Record({
  'principal' : IDL.Principal,
  'day28EmailSent' : IDL.Bool,
  'day28Dismissed' : IDL.Bool,
  'day26EmailSent' : IDL.Bool,
  'day26Dismissed' : IDL.Bool,
});
export const ResourceType = IDL.Variant({
  'equipment' : IDL.Null,
  'labor' : IDL.Null,
});
export const Resource = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'hourlyRate' : IDL.Float64,
  'idleTimeMode' : IdleTimeMode,
  'hourlyRateSource' : IDL.Text,
  'resourceType' : ResourceType,
  'csiCode' : IDL.Opt(IDL.Text),
  'crewSize' : IDL.Opt(IDL.Nat),
  'trackingLevel' : TrackingLevel,
});
export const ScenarioBenchmarkVariance = IDL.Record({
  'scenarioId' : ScenarioId,
  'divisionName' : IDL.Text,
  'variance' : IDL.Float64,
  'actualCost' : IDL.Float64,
  'variancePct' : IDL.Float64,
  'divisionId' : IDL.Nat,
  'rsMeansCost' : IDL.Float64,
});
export const ScenarioEVMSummary = IDL.Record({
  'cv' : IDL.Float64,
  'sv' : IDL.Float64,
  'cpi' : IDL.Float64,
  'spi' : IDL.Float64,
  'scenarioId' : ScenarioId,
  'plannedValue' : IDL.Float64,
  'earnedValue' : IDL.Float64,
  'actualCost' : IDL.Float64,
});
export const PhaseSignOffShared = IDL.Record({
  'id' : IDL.Text,
  'role' : IDL.Text,
  'signedAt' : IDL.Int,
  'signedBy' : IDL.Text,
  'approved' : IDL.Bool,
  'comments' : IDL.Text,
  'phaseId' : IDL.Text,
});
export const TrialLink = IDL.Record({
  'slug' : IDL.Text,
  'tier' : SubscriptionTier,
  'isActive' : IDL.Bool,
});
export const ZoomSettings = IDL.Record({
  'clientId' : IDL.Text,
  'fixedZoomLinks' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'clientSecret' : IDL.Text,
});
export const PhaseStandardLink = IDL.Record({
  'id' : IDL.Text,
  'linkedAt' : IDL.Int,
  'linkedBy' : IDL.Text,
  'standardId' : IDL.Text,
  'csiCode' : IDL.Text,
  'phaseId' : IDL.Text,
});
export const ScenarioSummary = IDL.Record({
  'id' : ScenarioId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
});
export const CostCodeInput = IDL.Record({
  'area' : IDL.Text,
  'cost' : IDL.Float64,
  'projectNumber' : IDL.Text,
  'operation' : IDL.Text,
  'csiCode' : IDL.Text,
  'distribution' : IDL.Text,
  'csiDivision' : IDL.Text,
});
export const PhaseInput = IDL.Record({
  'crashFactor' : IDL.Opt(IDL.Float64),
  'resourceMultiplier' : IDL.Opt(IDL.Float64),
  'name' : IDL.Text,
  'costCodes' : IDL.Opt(IDL.Vec(CostCodeInput)),
  'phaseOrder' : IDL.Nat,
  'scheduleOfValues' : IDL.Float64,
  'requiredCash' : IDL.Float64,
  'endOffset' : TimeOffset,
  'startOffset' : TimeOffset,
});
export const Result_2 = IDL.Variant({
  'ok' : CancellationRequest,
  'err' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const PhaseAllocationInput = IDL.Record({
  'allocatedHours' : IDL.Float64,
  'resourceId' : IDL.Text,
  'availableHours' : IDL.Float64,
  'manualLaborCost' : IDL.Opt(IDL.Float64),
  'actualHours' : IDL.Opt(IDL.Float64),
  'phaseId' : IDL.Text,
  'laborCostSource' : IDL.Text,
});
export const ResourceInput = IDL.Record({
  'name' : IDL.Text,
  'hourlyRate' : IDL.Float64,
  'idleTimeMode' : IDL.Opt(IdleTimeMode),
  'hourlyRateSource' : IDL.Text,
  'resourceType' : ResourceType,
  'csiCode' : IDL.Opt(IDL.Text),
  'crewSize' : IDL.Opt(IDL.Nat),
  'trackingLevel' : TrackingLevel,
});

export const idlService = IDL.Service({
  'activateSubscription' : IDL.Func([IDL.Text], [Result_1], []),
  'addDrawing' : IDL.Func(
      [IDL.Text, DrawingCategory, DrawingFileType, IDL.Text, IDL.Text],
      [Drawing],
      [],
    ),
  'addLoginEmail' : IDL.Func([IDL.Text], [Result], []),
  'addNCCERCertification' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Int,
      ],
      [NCCERCertShared],
      [],
    ),
  'addPaymentMethod' : IDL.Func([IDL.Text], [Result_1], []),
  'addRenewalHistoryEntry' : IDL.Func([RenewalHistoryEntry], [Result], []),
  'addUserLoginEmail' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'applyProjectTemplate' : IDL.Func(
      [IDL.Text, IDL.Text],
      [ApplyTemplateResult],
      [],
    ),
  'approveCancellationRequest' : IDL.Func([IDL.Text], [Result], []),
  'approveCriticalChangePlan' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [CriticalPlanApproval],
      [],
    ),
  'approveDocumentReview' : IDL.Func([IDL.Principal, IDL.Text], [Result], []),
  'approveParticipant' : IDL.Func([IDL.Text], [IDL.Opt(Participant)], []),
  'assignAdmin' : IDL.Func([IDL.Principal], [Result], []),
  'assignParticipantToPhaseCode' : IDL.Func(
      [ParticipantAssignment],
      [ParticipantAssignment],
      [],
    ),
  'autoLinkStandardsForCategory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Vec(IDL.Text)],
      [],
    ),
  'canAccessCompliance' : IDL.Func([ParticipantRole], [IDL.Bool], ['query']),
  'canManageCriticalPlans' : IDL.Func([ParticipantRole], [IDL.Bool], ['query']),
  'cancelTrial' : IDL.Func([], [Result], []),
  'changeControllerPassword' : IDL.Func([IDL.Text], [Result], []),
  'changePassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
  'claimController' : IDL.Func([], [Result], []),
  'compareScenarios' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(ScenarioCashProjection)],
      ['query'],
    ),
  'computeCriticalPath' : IDL.Func(
      [IDL.Vec(CPMPhaseInput)],
      [IDL.Vec(CriticalPathNode)],
      ['query'],
    ),
  'computeResourceSummaries' : IDL.Func(
      [IDL.Float64, IDL.Float64],
      [IDL.Vec(ResourceSummary)],
      ['query'],
    ),
  'createCriticalChangePlan' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [CriticalChangePlanShared],
      [],
    ),
  'createOACSession' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'createParticipant' : IDL.Func([Participant], [Participant], []),
  'createReviewRequest' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Tuple(ReviewRequest, DrawingNotification))],
      [],
    ),
  'createScenario' : IDL.Func(
      [CreateScenarioRequest],
      [IDL.Variant({ 'ok' : Scenario, 'err' : IDL.Text })],
      [],
    ),
  'deactivateShareLink' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteCostCode' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteDrawing' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteParticipant' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deletePhase' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deletePhaseAllocation' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteResource' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteReviewRequest' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteScenario' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'denyCancellationRequest' : IDL.Func([IDL.Text], [Result], []),
  'directCancelSubscription' : IDL.Func([IDL.Principal], [Result], []),
  'dismissDrawingNotification' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'dismissReminder' : IDL.Func([IDL.Nat], [], []),
  'emailLogin' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result_6],
      [],
    ),
  'emailOnlyLogin' : IDL.Func([IDL.Text], [Result_5], []),
  'endSession' : IDL.Func([IDL.Text], [], []),
  'enrollTrial' : IDL.Func(
      [SubscriptionTier, IDL.Text, IDL.Text],
      [Result_1],
      [],
    ),
  'expireSubscription' : IDL.Func([], [Result], []),
  'fetchRSMeansBenchmarks' : IDL.Func([IDL.Text], [IDL.Text], []),
  'freezeSubscription' : IDL.Func([IDL.Principal, IDL.Text], [Result], []),
  'generateResetCode' : IDL.Func([IDL.Text], [Result_5], []),
  'generateShareLink' : IDL.Func([IDL.Text], [ShareLink], []),
  'generateUserResetCode' : IDL.Func([IDL.Text], [Result_5], []),
  'generateZoomMeeting' : IDL.Func(
      [IDL.Text, IDL.Text],
      [ZoomMeetingResult],
      [],
    ),
  'getAIAForm' : IDL.Func([IDL.Text], [IDL.Opt(AIAFormEntry)], ['query']),
  'getAIAForms' : IDL.Func([IDL.Text], [IDL.Vec(AIAFormEntry)], ['query']),
  'getActiveFilter' : IDL.Func(
      [],
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getActiveSessions' : IDL.Func([], [IDL.Vec(SessionSnapshot)], ['query']),
  'getAdminList' : IDL.Func([], [IDL.Vec(AdminRole)], ['query']),
  'getAllCancellationRequests' : IDL.Func(
      [],
      [IDL.Vec(CancellationRequest)],
      ['query'],
    ),
  'getAllUsers' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'name' : IDL.Text,
            'createdAt' : IDL.Int,
            'email' : IDL.Text,
            'lastLogin' : IDL.Int,
          })
        ),
      ],
      ['query'],
    ),
  'getAppSettings' : IDL.Func([], [AppSettings], ['query']),
  'getBankAccount' : IDL.Func([], [IDL.Opt(BankAccount)], ['query']),
  'getCertificationsForPhase' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(NCCERCertShared)],
      ['query'],
    ),
  'getComplianceItemsForPhase' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ComplianceItemShared)],
      ['query'],
    ),
  'getControllerProfile' : IDL.Func([], [Result_4], ['query']),
  'getCostCodeCompletion' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Opt(IDL.Float64)],
      ['query'],
    ),
  'getCostCodesForPhase' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Vec(CostCode__1), 'err' : IDL.Text })],
      ['query'],
    ),
  'getCriticalChangePlansForPhase' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CriticalChangePlanShared)],
      ['query'],
    ),
  'getCumulativeCashRequirement' : IDL.Func(
      [],
      [IDL.Vec(CumulativePoint)],
      ['query'],
    ),
  'getCumulativeCrashedRequirement' : IDL.Func(
      [],
      [IDL.Vec(CumulativePoint)],
      ['query'],
    ),
  'getCumulativeWithBreakdown' : IDL.Func(
      [],
      [IDL.Vec(CumulativePointWithCodes)],
      ['query'],
    ),
  'getDocumentReviewStatus' : IDL.Func(
      [],
      [IDL.Vec(VerificationDocument)],
      ['query'],
    ),
  'getDrawingNotifications' : IDL.Func(
      [],
      [IDL.Vec(DrawingNotification)],
      ['query'],
    ),
  'getDrawings' : IDL.Func([], [IDL.Vec(Drawing)], ['query']),
  'getEarnedValueMetrics' : IDL.Func(
      [BaselineType],
      [IDL.Vec(EVMPoint)],
      ['query'],
    ),
  'getFeatureLocks' : IDL.Func([], [FeatureLockSnapshot], ['query']),
  'getFilteredStandards' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Vec(SafetyStandard)],
      ['query'],
    ),
  'getIdleTimeSetting' : IDL.Func([], [IDL.Opt(IdleTimeSetting)], ['query']),
  'getLoginEmails' : IDL.Func([], [Result_3], ['query']),
  'getLoginHistory' : IDL.Func([], [IDL.Vec(SessionSnapshot)], ['query']),
  'getNCCERCertificationsForParticipant' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(NCCERCertShared)],
      ['query'],
    ),
  'getNextPayoutDate' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getOACSession' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(OACMeetingSession)],
      ['query'],
    ),
  'getOACSessions' : IDL.Func([], [IDL.Vec(OACMeetingSession)], ['query']),
  'getParticipant' : IDL.Func([IDL.Text], [IDL.Opt(Participant)], ['query']),
  'getParticipantAssignments' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ParticipantAssignment)],
      ['query'],
    ),
  'getParticipantMeetingPackage' : IDL.Func(
      [IDL.Text],
      [MeetingPackage],
      ['query'],
    ),
  'getParticipants' : IDL.Func([], [IDL.Vec(Participant)], ['query']),
  'getPaymentMethods' : IDL.Func([], [IDL.Vec(PaymentMethodInfo)], ['query']),
  'getPayoutRecords' : IDL.Func([], [IDL.Vec(PayoutRecord)], ['query']),
  'getPhaseAllocations' : IDL.Func([], [IDL.Vec(PhaseAllocation)], ['query']),
  'getPhaseAllocationsByPhase' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PhaseAllocation)],
      ['query'],
    ),
  'getPhaseAllocationsByResource' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PhaseAllocation)],
      ['query'],
    ),
  'getPhaseComplianceStatus' : IDL.Func(
      [IDL.Text],
      [PhaseComplianceSummary],
      ['query'],
    ),
  'getPhases' : IDL.Func([], [IDL.Vec(Phase)], ['query']),
  'getProjectCategories' : IDL.Func([], [IDL.Vec(ProjectCategory)], ['query']),
  'getProjectEVMSummary' : IDL.Func(
      [BaselineType],
      [ProjectEVMSummary],
      ['query'],
    ),
  'getProjectShareLinks' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ShareLink)],
      ['query'],
    ),
  'getProjectSubtopic' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(ProjectSubtopic)],
      ['query'],
    ),
  'getRSMeansSettings' : IDL.Func([], [RSMeansSettings], ['query']),
  'getReminderState' : IDL.Func([], [IDL.Opt(ReminderState)], ['query']),
  'getRenewalHistory' : IDL.Func([], [IDL.Vec(RenewalHistoryEntry)], ['query']),
  'getResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
  'getResourcesByType' : IDL.Func(
      [ResourceType],
      [IDL.Vec(Resource)],
      ['query'],
    ),
  'getReviewRequests' : IDL.Func([], [IDL.Vec(ReviewRequest)], ['query']),
  'getScenario' : IDL.Func([IDL.Text], [IDL.Opt(Scenario)], ['query']),
  'getScenarioBenchmarkVariances' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ScenarioBenchmarkVariance)],
      ['query'],
    ),
  'getScenarioCashProjection' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ScenarioCashProjection)],
      ['query'],
    ),
  'getScenarioEVMSummary' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ScenarioEVMSummary)],
      ['query'],
    ),
  'getShareLink' : IDL.Func([IDL.Text], [IDL.Opt(ShareLink)], ['query']),
  'getSignOffsForPhase' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PhaseSignOffShared)],
      ['query'],
    ),
  'getStandard' : IDL.Func([IDL.Text], [IDL.Opt(SafetyStandard)], ['query']),
  'getStandardsForCsiCode' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SafetyStandard)],
      ['query'],
    ),
  'getStandardsForPhase' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SafetyStandard)],
      ['query'],
    ),
  'getSubscriptionStatus' : IDL.Func([], [SubscriptionStatus], ['query']),
  'getTrialLinks' : IDL.Func([], [IDL.Vec(TrialLink)], ['query']),
  'getUserCancellationRequests' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CancellationRequest)],
      ['query'],
    ),
  'getUserLoginEmails' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getUserSubscription' : IDL.Func([], [IDL.Opt(UserSubscription)], ['query']),
  'getZoomSettings' : IDL.Func([], [IDL.Opt(ZoomSettings)], ['query']),
  'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isController' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isPhaseSignedOff' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isPlanFullyApproved' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'linkStandardToPhase' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [PhaseStandardLink],
      [],
    ),
  'listScenarios' : IDL.Func([], [IDL.Vec(ScenarioSummary)], ['query']),
  'registerEmailUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'rejectParticipant' : IDL.Func([IDL.Text], [IDL.Opt(Participant)], []),
  'removeLoginEmail' : IDL.Func([IDL.Text], [Result], []),
  'removeParticipantAssignment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'removeUserLoginEmail' : IDL.Func([IDL.Text], [Result], []),
  'renewSubscription' : IDL.Func([], [Result_1], []),
  'resendPasscode' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'revokeAdmin' : IDL.Func([IDL.Principal], [Result], []),
  'saveAIAForm' : IDL.Func(
      [IDL.Text, FormType, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)), IDL.Text],
      [IDL.Text],
      [],
    ),
  'saveAppSettings' : IDL.Func([AppSettings], [AppSettings], []),
  'saveBankAccount' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'savePayoutRecords' : IDL.Func([IDL.Vec(PayoutRecord)], [], []),
  'saveRSMeansSettings' : IDL.Func([RSMeansSettings], [RSMeansSettings], []),
  'saveZoomSettings' : IDL.Func([ZoomSettings], [IDL.Bool], []),
  'searchStandards' : IDL.Func(
      [IDL.Text, IDL.Opt(StandardCategory), IDL.Opt(IDL.Text)],
      [IDL.Vec(SafetyStandard)],
      ['query'],
    ),
  'setActiveFilter' : IDL.Func([IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)], [], []),
  'setFeatureLock' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setFixedZoomLink' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'setIdleTimeSetting' : IDL.Func([IdleTimeMode], [IdleTimeSetting], []),
  'setNextPayoutDate' : IDL.Func([IDL.Text], [], []),
  'setPhases' : IDL.Func([IDL.Vec(PhaseInput)], [], []),
  'setReminderEmailSent' : IDL.Func([IDL.Nat], [], []),
  'setStripeSecretKey' : IDL.Func([IDL.Text], [], []),
  'submitCancellationRequest' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
  'submitDocumentForReview' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [VerificationDocument],
      [],
    ),
  'submitPhaseSignOff' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Text],
      [PhaseSignOffShared],
      [],
    ),
  'submitPlanForApproval' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CriticalChangePlanShared)],
      [],
    ),
  'switchTrialTier' : IDL.Func([SubscriptionTier], [Result_1], []),
  'testRSMeansConnection' : IDL.Func([], [IDL.Text], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unfreezeSubscription' : IDL.Func([IDL.Principal], [Result], []),
  'unlinkStandardFromPhase' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateAIAForm' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      [IDL.Bool],
      [],
    ),
  'updateControllerProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'updateCostCodeCompletion' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Float64],
      [],
      [],
    ),
  'updateCriticalChangePlan' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Vec(IDL.Text)),
        IDL.Opt(IDL.Vec(IDL.Text)),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Vec(IDL.Text)),
        IDL.Opt(IDL.Vec(IDL.Text)),
      ],
      [IDL.Opt(CriticalChangePlanShared)],
      [],
    ),
  'updateNCCERCertification' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Int),
        IDL.Opt(NCCERCertStatus),
      ],
      [IDL.Opt(NCCERCertShared)],
      [],
    ),
  'updateOACSessionZoomLink' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateParticipant' : IDL.Func([Participant], [IDL.Opt(Participant)], []),
  'updateRSMeansEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ParticipantAssignment],
      [IDL.Opt(ParticipantAssignment)],
      [],
    ),
  'updateReviewRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(ReviewRequest)],
      [],
    ),
  'updateScenario' : IDL.Func(
      [IDL.Text, CreateScenarioRequest],
      [IDL.Variant({ 'ok' : Scenario, 'err' : IDL.Text })],
      [],
    ),
  'upsertComplianceItem' : IDL.Func(
      [IDL.Text, IDL.Text, ComplianceStatus, ComplianceSeverity, IDL.Text],
      [ComplianceItemShared],
      [],
    ),
  'upsertCostCode' : IDL.Func(
      [IDL.Nat, CostCodeInput],
      [IDL.Variant({ 'ok' : CostCode__1, 'err' : IDL.Text })],
      [],
    ),
  'upsertPhase' : IDL.Func([IDL.Nat, PhaseInput], [Phase], []),
  'upsertPhaseAllocation' : IDL.Func(
      [PhaseAllocationInput],
      [PhaseAllocation],
      [],
    ),
  'upsertResource' : IDL.Func([ResourceInput], [Resource], []),
  'validateResetCode' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
  'zoomTransform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SubscriptionStatus = IDL.Variant({
    'trial' : IDL.Null,
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'expired' : IDL.Null,
    'frozen' : IDL.Null,
  });
  const SubscriptionTier = IDL.Variant({
    'tier10year' : IDL.Null,
    'tier1year' : IDL.Null,
    'tier5year' : IDL.Null,
  });
  const UserSubscription = IDL.Record({
    'status' : SubscriptionStatus,
    'frozenReason' : IDL.Opt(IDL.Text),
    'trialStartAt' : IDL.Int,
    'frozenAt' : IDL.Opt(IDL.Int),
    'stripeSubscriptionId' : IDL.Opt(IDL.Text),
    'userId' : IDL.Principal,
    'subscriptionStartAt' : IDL.Opt(IDL.Int),
    'tier' : SubscriptionTier,
    'cancelledAt' : IDL.Opt(IDL.Int),
    'currentPlan' : SubscriptionTier,
    'stripeCustomerId' : IDL.Opt(IDL.Text),
    'chargeScheduledAt' : IDL.Int,
    'subscriptionExpiresAt' : IDL.Opt(IDL.Int),
    'stripePaymentMethodId' : IDL.Opt(IDL.Text),
  });
  const Result_1 = IDL.Variant({ 'ok' : UserSubscription, 'err' : IDL.Text });
  const DrawingCategory = IDL.Variant({
    'ArchitectDrawings' : IDL.Null,
    'ConstructionDrawings' : IDL.Null,
    'CADFiles' : IDL.Null,
    'Blueprints' : IDL.Null,
    'Photographs' : IDL.Null,
    'EngineeringDrawings' : IDL.Null,
  });
  const DrawingFileType = IDL.Variant({
    'DWG' : IDL.Null,
    'DXF' : IDL.Null,
    'JPG' : IDL.Null,
    'PDF' : IDL.Null,
    'PNG' : IDL.Null,
  });
  const Drawing = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'fileType' : DrawingFileType,
    'storageKey' : IDL.Text,
    'category' : DrawingCategory,
    'uploadedAt' : IDL.Int,
    'uploadedBy' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const NCCERCertStatus = IDL.Variant({
    'Expiring' : IDL.Null,
    'Current' : IDL.Null,
    'Expired' : IDL.Null,
  });
  const NCCERCertShared = IDL.Record({
    'id' : IDL.Text,
    'status' : NCCERCertStatus,
    'trade' : IDL.Text,
    'expiresAt' : IDL.Int,
    'discipline' : IDL.Text,
    'level' : IDL.Text,
    'state' : IDL.Text,
    'participantId' : IDL.Text,
    'certNumber' : IDL.Text,
    'issuedAt' : IDL.Int,
  });
  const RenewalHistoryEntry = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'Failed' : IDL.Null,
      'Paid' : IDL.Null,
      'Cancelled' : IDL.Null,
      'Pending' : IDL.Null,
    }),
    'principal' : IDL.Principal,
    'monthlyCharge' : IDL.Nat,
    'endDate' : IDL.Int,
    'createdAt' : IDL.Int,
    'tier' : SubscriptionTier,
    'totalPaid' : IDL.Nat,
    'startDate' : IDL.Int,
  });
  const ApplyTemplateResult = IDL.Variant({
    'ok' : IDL.Record({ 'phasesCreated' : IDL.Nat }),
    'err' : IDL.Text,
  });
  const CriticalPlanApproval = IDL.Record({
    'id' : IDL.Text,
    'planId' : IDL.Text,
    'approvedAt' : IDL.Int,
    'approvedBy' : IDL.Text,
    'role' : IDL.Text,
    'approved' : IDL.Bool,
  });
  const ParticipantStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const ParticipantRole = IDL.Variant({
    'EHSRepresentative' : IDL.Null,
    'Designer' : IDL.Null,
    'MechanicalEngineer' : IDL.Null,
    'Architect' : IDL.Null,
    'SpecialtyEngineer' : IDL.Null,
    'SafetyEngineer' : IDL.Null,
    'SafetyInspector' : IDL.Null,
    'CivilEngineer' : IDL.Null,
    'ConstructionManager' : IDL.Null,
    'Owner' : IDL.Null,
    'Contractor' : IDL.Null,
  });
  const Participant = IDL.Record({
    'id' : IDL.Text,
    'status' : ParticipantStatus,
    'companyTrade' : IDL.Text,
    'passcodeEmailSent' : IDL.Bool,
    'passcode' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'role' : ParticipantRole,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'notes' : IDL.Text,
    'companyName' : IDL.Text,
    'mobilePhone' : IDL.Text,
    'officePhone' : IDL.Text,
    'companyAddress' : IDL.Text,
    'residentialAddress' : IDL.Text,
  });
  const RSMeansSource = IDL.Variant({
    'None' : IDL.Null,
    'ManualEntry' : IDL.Null,
    'LiveAPI' : IDL.Null,
  });
  const ParticipantAssignment = IDL.Record({
    'costCodeId' : IDL.Text,
    'variance' : IDL.Opt(IDL.Float64),
    'actualCost' : IDL.Opt(IDL.Float64),
    'rsMeansCrewRate' : IDL.Opt(IDL.Float64),
    'participantId' : IDL.Text,
    'rsMeansMaterialRate' : IDL.Opt(IDL.Float64),
    'rsMeansEquipmentRate' : IDL.Opt(IDL.Float64),
    'rsMeansUnitCost' : IDL.Opt(IDL.Float64),
    'rsMeansSource' : RSMeansSource,
    'rsMeansLaborRate' : IDL.Opt(IDL.Float64),
    'phaseId' : IDL.Text,
  });
  const ScenarioId = IDL.Text;
  const ScenarioCashProjection = IDL.Record({
    'cumulativePoints' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Float64)),
    'scenarioId' : ScenarioId,
    'scenarioName' : IDL.Text,
    'totalCost' : IDL.Float64,
  });
  const CPMPhaseInput = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'endOffset' : IDL.Float64,
    'dependencies' : IDL.Vec(IDL.Text),
    'startOffset' : IDL.Float64,
  });
  const CriticalPathNode = IDL.Record({
    'lateFinish' : IDL.Float64,
    'earlyFinish' : IDL.Float64,
    'isCritical' : IDL.Bool,
    'earlyStart' : IDL.Float64,
    'totalSlack' : IDL.Float64,
    'phaseName' : IDL.Text,
    'phaseId' : IDL.Text,
    'lateStart' : IDL.Float64,
  });
  const TrackingLevel = IDL.Variant({
    'crew' : IDL.Null,
    'individual' : IDL.Null,
  });
  const ResourceSummary = IDL.Record({
    'resourceId' : IDL.Text,
    'totalIdleHours' : IDL.Float64,
    'idleHoursCrashedBaseline' : IDL.Float64,
    'idleHoursOriginalBaseline' : IDL.Float64,
    'resourceName' : IDL.Text,
    'totalLaborCost' : IDL.Float64,
    'totalAllocatedHours' : IDL.Float64,
    'trackingLevel' : TrackingLevel,
    'totalAvailableHours' : IDL.Float64,
  });
  const CriticalPlanStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Draft' : IDL.Null,
    'Rejected' : IDL.Null,
    'PendingApproval' : IDL.Null,
  });
  const CriticalChangePlanShared = IDL.Record({
    'id' : IDL.Text,
    'status' : CriticalPlanStatus,
    'phaseIds' : IDL.Vec(IDL.Text),
    'responsibleParticipantIds' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Text,
    'affectedStandardIds' : IDL.Vec(IDL.Text),
    'hazardAnalysis' : IDL.Text,
    'controlMeasures' : IDL.Text,
    'csiCodes' : IDL.Vec(IDL.Text),
  });
  const ReviewRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'oacFormId' : IDL.Opt(IDL.Text),
    'notes' : IDL.Text,
    'requestedAt' : IDL.Int,
    'requestedBy' : IDL.Text,
    'drawingId' : IDL.Text,
  });
  const DrawingNotification = IDL.Record({
    'id' : IDL.Text,
    'drawingName' : IDL.Text,
    'dismissed' : IDL.Bool,
    'requestedAt' : IDL.Int,
    'requestedBy' : IDL.Text,
    'drawingId' : IDL.Text,
  });
  const PhaseOverride = IDL.Record({
    'crashFactor' : IDL.Float64,
    'resourceMultiplier' : IDL.Float64,
    'laborCostOverride' : IDL.Opt(IDL.Float64),
    'phaseId' : IDL.Text,
  });
  const ParticipantOverride = IDL.Record({
    'participantId' : IDL.Text,
    'costCodeAssignments' : IDL.Vec(IDL.Text),
    'phaseAssignments' : IDL.Vec(IDL.Text),
    'newRole' : IDL.Opt(IDL.Text),
  });
  const CreateScenarioRequest = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'phaseOverrides' : IDL.Vec(PhaseOverride),
    'participantOverrides' : IDL.Vec(ParticipantOverride),
  });
  const Scenario = IDL.Record({
    'id' : ScenarioId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'phaseOverrides' : IDL.Vec(PhaseOverride),
    'participantOverrides' : IDL.Vec(ParticipantOverride),
  });
  const Result_6 = IDL.Variant({
    'ok' : IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text }),
    'err' : IDL.Text,
  });
  const Result_5 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const ShareLink = IDL.Record({
    'id' : IDL.Text,
    'token' : IDL.Text,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'projectId' : IDL.Text,
  });
  const ZoomMeetingResult = IDL.Variant({
    'ok' : IDL.Record({ 'joinUrl' : IDL.Text, 'meetingId' : IDL.Text }),
    'err' : IDL.Text,
  });
  const FormType = IDL.Variant({
    'MeetingMinutes' : IDL.Null,
    'G701' : IDL.Null,
    'G702' : IDL.Null,
    'G703' : IDL.Null,
    'Addendum' : IDL.Null,
  });
  const AIAFormEntry = IDL.Record({
    'id' : IDL.Text,
    'submittedByRole' : IDL.Text,
    'submittedAt' : IDL.Int,
    'formType' : FormType,
    'lastModified' : IDL.Int,
    'sessionId' : IDL.Text,
    'fieldData' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  });
  const SessionSnapshot = IDL.Record({
    'principal' : IDL.Principal,
    'lastActivity' : IDL.Int,
    'isActive' : IDL.Bool,
    'timestamp' : IDL.Int,
    'sessionId' : IDL.Text,
    'userAgent' : IDL.Text,
    'ipAddress' : IDL.Text,
  });
  const AdminRole = IDL.Record({
    'assignedAt' : IDL.Int,
    'assignedBy' : IDL.Principal,
    'assignedPrincipal' : IDL.Principal,
  });
  const CancellationRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'denied' : IDL.Null,
    'approved' : IDL.Null,
  });
  const CancellationRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : CancellationRequestStatus,
    'email' : IDL.Text,
    'subscriberPrincipal' : IDL.Principal,
    'requestedAt' : IDL.Int,
    'reason' : IDL.Text,
  });
  const RSMeansSettings = IDL.Record({
    'apiKey' : IDL.Opt(IDL.Text),
    'lastTestStatus' : IDL.Opt(IDL.Text),
    'apiEnabled' : IDL.Bool,
  });
  const AccessControlMode = IDL.Variant({
    'RoleGated' : IDL.Null,
    'ProjectManagerOnly' : IDL.Null,
  });
  const AppSettings = IDL.Record({
    'activeCategoryId' : IDL.Opt(IDL.Text),
    'projectManagerId' : IDL.Opt(IDL.Text),
    'rsMeansSettings' : RSMeansSettings,
    'activeSubtopicId' : IDL.Opt(IDL.Text),
    'accessControlMode' : AccessControlMode,
  });
  const BankAccount = IDL.Record({
    'nextPayoutDate' : IDL.Opt(IDL.Text),
    'routingNumber' : IDL.Text,
    'accountHolderName' : IDL.Text,
    'connectedToStripe' : IDL.Bool,
    'isVerified' : IDL.Bool,
    'accountNumberLast4' : IDL.Text,
  });
  const ComplianceStatus = IDL.Variant({
    'NA' : IDL.Null,
    'NonCompliant' : IDL.Null,
    'Compliant' : IDL.Null,
  });
  const ComplianceSeverity = IDL.Variant({
    'None' : IDL.Null,
    'Critical' : IDL.Null,
    'Major' : IDL.Null,
    'Minor' : IDL.Null,
  });
  const ComplianceItemShared = IDL.Record({
    'id' : IDL.Text,
    'status' : ComplianceStatus,
    'notes' : IDL.Text,
    'standardId' : IDL.Text,
    'checkedAt' : IDL.Int,
    'checkedBy' : IDL.Text,
    'severity' : ComplianceSeverity,
    'phaseId' : IDL.Text,
  });
  const Result_4 = IDL.Variant({
    'ok' : IDL.Record({
      'name' : IDL.Text,
      'email' : IDL.Text,
      'phone' : IDL.Text,
    }),
    'err' : IDL.Text,
  });
  const CostCodeId = IDL.Nat;
  const CostCode__1 = IDL.Record({
    'id' : CostCodeId,
    'area' : IDL.Text,
    'cost' : IDL.Float64,
    'projectNumber' : IDL.Text,
    'operation' : IDL.Text,
    'csiCode' : IDL.Text,
    'distribution' : IDL.Text,
    'csiDivision' : IDL.Text,
    'phaseId' : IDL.Nat,
  });
  const TimeOffset = IDL.Int;
  const CumulativePoint = IDL.Record({
    'crashedCash' : IDL.Float64,
    'phaseOrder' : IDL.Nat,
    'cumulativeSOV' : IDL.Float64,
    'cumulativeCash' : IDL.Float64,
    'phaseName' : IDL.Text,
    'endOffset' : TimeOffset,
  });
  const CostCodeBreakdown = IDL.Record({
    'cumulativeCost' : IDL.Float64,
    'csiCode' : IDL.Text,
    'csiDivision' : IDL.Text,
  });
  const CumulativePointWithCodes = IDL.Record({
    'crashedCash' : IDL.Float64,
    'breakdown' : IDL.Vec(CostCodeBreakdown),
    'phaseOrder' : IDL.Nat,
    'cumulativeSOV' : IDL.Float64,
    'cumulativeCash' : IDL.Float64,
    'phaseName' : IDL.Text,
    'endOffset' : TimeOffset,
  });
  const VerificationDocument = IDL.Record({
    'documentType' : IDL.Text,
    'stripeVerificationSessionId' : IDL.Opt(IDL.Text),
    'storageKey' : IDL.Text,
    'stripeVerificationStatus' : IDL.Text,
    'adminReviewStatus' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const BaselineType = IDL.Variant({
    'crashed' : IDL.Null,
    'original' : IDL.Null,
  });
  const EVMPoint = IDL.Record({
    'cpi' : IDL.Float64,
    'spi' : IDL.Float64,
    'baselineType' : BaselineType,
    'phaseOrder' : IDL.Nat,
    'plannedValue' : IDL.Float64,
    'earnedValue' : IDL.Float64,
    'productivityIndex' : IDL.Float64,
    'actualCost' : IDL.Float64,
    'costVariance' : IDL.Float64,
    'customProductivityIndex' : IDL.Opt(IDL.Float64),
    'phaseName' : IDL.Text,
    'scheduleVariance' : IDL.Float64,
    'phaseId' : IDL.Nat,
  });
  const FeatureLockSnapshot = IDL.Record({
    'subscriptions' : IDL.Bool,
    'participants' : IDL.Bool,
    'documents' : IDL.Bool,
    'resources' : IDL.Bool,
    'scheduling' : IDL.Bool,
    'cost' : IDL.Bool,
    'compliance' : IDL.Bool,
    'oacMeetings' : IDL.Bool,
  });
  const StandardStatus = IDL.Variant({
    'Superseded' : IDL.Null,
    'Active' : IDL.Null,
    'Withdrawn' : IDL.Null,
  });
  const StandardCategory = IDL.Variant({
    'IBC' : IDL.Null,
    'NCCER' : IDL.Null,
    'ANSI' : IDL.Null,
    'IEEE' : IDL.Null,
    'OSHA' : IDL.Null,
  });
  const SafetyStandard = IDL.Record({
    'id' : IDL.Text,
    'status' : StandardStatus,
    'title' : IDL.Text,
    'code' : IDL.Text,
    'csiDivisions' : IDL.Vec(IDL.Text),
    'summary' : IDL.Text,
    'state' : IDL.Opt(IDL.Text),
    'relatedStandards' : IDL.Vec(IDL.Text),
    'category' : StandardCategory,
    'applicableTrades' : IDL.Vec(IDL.Text),
  });
  const IdleTimeMode = IDL.Variant({
    'holdThroughProject' : IDL.Null,
    'releaseAtPhaseEnd' : IDL.Null,
  });
  const IdleTimeSetting = IDL.Record({
    'defaultIdleMode' : IdleTimeMode,
    'projectId' : IDL.Text,
  });
  const Result_3 = IDL.Variant({ 'ok' : IDL.Vec(IDL.Text), 'err' : IDL.Text });
  const OACMeetingSession = IDL.Record({
    'id' : IDL.Text,
    'zoomMeetingId' : IDL.Opt(IDL.Text),
    'sessionDate' : IDL.Text,
    'linkedCategoryId' : IDL.Opt(IDL.Text),
    'sessionTime' : IDL.Text,
    'createdAt' : IDL.Int,
    'projectId' : IDL.Text,
    'zoomLink' : IDL.Opt(IDL.Text),
  });
  const MeetingPackage = IDL.Record({
    'participants' : IDL.Vec(IDL.Text),
    'date' : IDL.Text,
    'link' : IDL.Text,
    'time' : IDL.Text,
  });
  const PaymentMethodInfo = IDL.Record({
    'expYear' : IDL.Nat,
    'paymentMethodId' : IDL.Text,
    'last4' : IDL.Text,
    'expMonth' : IDL.Nat,
    'isDefault' : IDL.Bool,
    'brand' : IDL.Text,
  });
  const PayoutRecord = IDL.Record({
    'status' : IDL.Text,
    'date' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const PhaseAllocation = IDL.Record({
    'id' : IDL.Text,
    'allocatedHours' : IDL.Float64,
    'resourceId' : IDL.Text,
    'availableHours' : IDL.Float64,
    'manualLaborCost' : IDL.Opt(IDL.Float64),
    'actualHours' : IDL.Opt(IDL.Float64),
    'phaseId' : IDL.Text,
    'laborCostSource' : IDL.Text,
  });
  const PhaseComplianceSummary = IDL.Record({
    'total' : IDL.Nat,
    'compliant' : IDL.Nat,
    'signedOff' : IDL.Bool,
    'nonCompliant' : IDL.Nat,
    'notApplicable' : IDL.Nat,
    'phaseId' : IDL.Text,
  });
  const PhaseId = IDL.Nat;
  const CostCode = IDL.Record({
    'id' : IDL.Nat,
    'area' : IDL.Text,
    'cost' : IDL.Float64,
    'projectNumber' : IDL.Text,
    'operation' : IDL.Text,
    'csiCode' : IDL.Text,
    'distribution' : IDL.Text,
    'csiDivision' : IDL.Text,
    'phaseId' : IDL.Nat,
  });
  const Phase = IDL.Record({
    'id' : PhaseId,
    'crashFactor' : IDL.Float64,
    'resourceMultiplier' : IDL.Float64,
    'name' : IDL.Text,
    'costCodes' : IDL.Vec(CostCode),
    'phaseOrder' : IDL.Nat,
    'scheduleOfValues' : IDL.Float64,
    'requiredCash' : IDL.Float64,
    'endOffset' : TimeOffset,
    'startOffset' : TimeOffset,
  });
  const DefaultPhase = IDL.Record({
    'durationDays' : IDL.Nat,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'csiDivisions' : IDL.Vec(IDL.Nat),
  });
  const ProjectSubtopic = IDL.Record({
    'id' : IDL.Text,
    'defaultCostCodeDivisions' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
    'defaultPhases' : IDL.Vec(DefaultPhase),
  });
  const ProjectCategory = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'subtopics' : IDL.Vec(ProjectSubtopic),
  });
  const ProjectEVMSummary = IDL.Record({
    'totalAC' : IDL.Float64,
    'totalCV' : IDL.Float64,
    'totalEV' : IDL.Float64,
    'totalPV' : IDL.Float64,
    'totalSV' : IDL.Float64,
    'projectPI' : IDL.Float64,
    'projectCPI' : IDL.Float64,
    'projectSPI' : IDL.Float64,
  });
  const ReminderState = IDL.Record({
    'principal' : IDL.Principal,
    'day28EmailSent' : IDL.Bool,
    'day28Dismissed' : IDL.Bool,
    'day26EmailSent' : IDL.Bool,
    'day26Dismissed' : IDL.Bool,
  });
  const ResourceType = IDL.Variant({
    'equipment' : IDL.Null,
    'labor' : IDL.Null,
  });
  const Resource = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'hourlyRate' : IDL.Float64,
    'idleTimeMode' : IdleTimeMode,
    'hourlyRateSource' : IDL.Text,
    'resourceType' : ResourceType,
    'csiCode' : IDL.Opt(IDL.Text),
    'crewSize' : IDL.Opt(IDL.Nat),
    'trackingLevel' : TrackingLevel,
  });
  const ScenarioBenchmarkVariance = IDL.Record({
    'scenarioId' : ScenarioId,
    'divisionName' : IDL.Text,
    'variance' : IDL.Float64,
    'actualCost' : IDL.Float64,
    'variancePct' : IDL.Float64,
    'divisionId' : IDL.Nat,
    'rsMeansCost' : IDL.Float64,
  });
  const ScenarioEVMSummary = IDL.Record({
    'cv' : IDL.Float64,
    'sv' : IDL.Float64,
    'cpi' : IDL.Float64,
    'spi' : IDL.Float64,
    'scenarioId' : ScenarioId,
    'plannedValue' : IDL.Float64,
    'earnedValue' : IDL.Float64,
    'actualCost' : IDL.Float64,
  });
  const PhaseSignOffShared = IDL.Record({
    'id' : IDL.Text,
    'role' : IDL.Text,
    'signedAt' : IDL.Int,
    'signedBy' : IDL.Text,
    'approved' : IDL.Bool,
    'comments' : IDL.Text,
    'phaseId' : IDL.Text,
  });
  const TrialLink = IDL.Record({
    'slug' : IDL.Text,
    'tier' : SubscriptionTier,
    'isActive' : IDL.Bool,
  });
  const ZoomSettings = IDL.Record({
    'clientId' : IDL.Text,
    'fixedZoomLinks' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'clientSecret' : IDL.Text,
  });
  const PhaseStandardLink = IDL.Record({
    'id' : IDL.Text,
    'linkedAt' : IDL.Int,
    'linkedBy' : IDL.Text,
    'standardId' : IDL.Text,
    'csiCode' : IDL.Text,
    'phaseId' : IDL.Text,
  });
  const ScenarioSummary = IDL.Record({
    'id' : ScenarioId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
  });
  const CostCodeInput = IDL.Record({
    'area' : IDL.Text,
    'cost' : IDL.Float64,
    'projectNumber' : IDL.Text,
    'operation' : IDL.Text,
    'csiCode' : IDL.Text,
    'distribution' : IDL.Text,
    'csiDivision' : IDL.Text,
  });
  const PhaseInput = IDL.Record({
    'crashFactor' : IDL.Opt(IDL.Float64),
    'resourceMultiplier' : IDL.Opt(IDL.Float64),
    'name' : IDL.Text,
    'costCodes' : IDL.Opt(IDL.Vec(CostCodeInput)),
    'phaseOrder' : IDL.Nat,
    'scheduleOfValues' : IDL.Float64,
    'requiredCash' : IDL.Float64,
    'endOffset' : TimeOffset,
    'startOffset' : TimeOffset,
  });
  const Result_2 = IDL.Variant({
    'ok' : CancellationRequest,
    'err' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const PhaseAllocationInput = IDL.Record({
    'allocatedHours' : IDL.Float64,
    'resourceId' : IDL.Text,
    'availableHours' : IDL.Float64,
    'manualLaborCost' : IDL.Opt(IDL.Float64),
    'actualHours' : IDL.Opt(IDL.Float64),
    'phaseId' : IDL.Text,
    'laborCostSource' : IDL.Text,
  });
  const ResourceInput = IDL.Record({
    'name' : IDL.Text,
    'hourlyRate' : IDL.Float64,
    'idleTimeMode' : IDL.Opt(IdleTimeMode),
    'hourlyRateSource' : IDL.Text,
    'resourceType' : ResourceType,
    'csiCode' : IDL.Opt(IDL.Text),
    'crewSize' : IDL.Opt(IDL.Nat),
    'trackingLevel' : TrackingLevel,
  });
  
  return IDL.Service({
    'activateSubscription' : IDL.Func([IDL.Text], [Result_1], []),
    'addDrawing' : IDL.Func(
        [IDL.Text, DrawingCategory, DrawingFileType, IDL.Text, IDL.Text],
        [Drawing],
        [],
      ),
    'addLoginEmail' : IDL.Func([IDL.Text], [Result], []),
    'addNCCERCertification' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Int,
        ],
        [NCCERCertShared],
        [],
      ),
    'addPaymentMethod' : IDL.Func([IDL.Text], [Result_1], []),
    'addRenewalHistoryEntry' : IDL.Func([RenewalHistoryEntry], [Result], []),
    'addUserLoginEmail' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'applyProjectTemplate' : IDL.Func(
        [IDL.Text, IDL.Text],
        [ApplyTemplateResult],
        [],
      ),
    'approveCancellationRequest' : IDL.Func([IDL.Text], [Result], []),
    'approveCriticalChangePlan' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [CriticalPlanApproval],
        [],
      ),
    'approveDocumentReview' : IDL.Func([IDL.Principal, IDL.Text], [Result], []),
    'approveParticipant' : IDL.Func([IDL.Text], [IDL.Opt(Participant)], []),
    'assignAdmin' : IDL.Func([IDL.Principal], [Result], []),
    'assignParticipantToPhaseCode' : IDL.Func(
        [ParticipantAssignment],
        [ParticipantAssignment],
        [],
      ),
    'autoLinkStandardsForCategory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Vec(IDL.Text)],
        [],
      ),
    'canAccessCompliance' : IDL.Func([ParticipantRole], [IDL.Bool], ['query']),
    'canManageCriticalPlans' : IDL.Func(
        [ParticipantRole],
        [IDL.Bool],
        ['query'],
      ),
    'cancelTrial' : IDL.Func([], [Result], []),
    'changeControllerPassword' : IDL.Func([IDL.Text], [Result], []),
    'changePassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
    'claimController' : IDL.Func([], [Result], []),
    'compareScenarios' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(ScenarioCashProjection)],
        ['query'],
      ),
    'computeCriticalPath' : IDL.Func(
        [IDL.Vec(CPMPhaseInput)],
        [IDL.Vec(CriticalPathNode)],
        ['query'],
      ),
    'computeResourceSummaries' : IDL.Func(
        [IDL.Float64, IDL.Float64],
        [IDL.Vec(ResourceSummary)],
        ['query'],
      ),
    'createCriticalChangePlan' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [CriticalChangePlanShared],
        [],
      ),
    'createOACSession' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'createParticipant' : IDL.Func([Participant], [Participant], []),
    'createReviewRequest' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Tuple(ReviewRequest, DrawingNotification))],
        [],
      ),
    'createScenario' : IDL.Func(
        [CreateScenarioRequest],
        [IDL.Variant({ 'ok' : Scenario, 'err' : IDL.Text })],
        [],
      ),
    'deactivateShareLink' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteCostCode' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteDrawing' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteParticipant' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deletePhase' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deletePhaseAllocation' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteResource' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteReviewRequest' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteScenario' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'denyCancellationRequest' : IDL.Func([IDL.Text], [Result], []),
    'directCancelSubscription' : IDL.Func([IDL.Principal], [Result], []),
    'dismissDrawingNotification' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'dismissReminder' : IDL.Func([IDL.Nat], [], []),
    'emailLogin' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result_6],
        [],
      ),
    'emailOnlyLogin' : IDL.Func([IDL.Text], [Result_5], []),
    'endSession' : IDL.Func([IDL.Text], [], []),
    'enrollTrial' : IDL.Func(
        [SubscriptionTier, IDL.Text, IDL.Text],
        [Result_1],
        [],
      ),
    'expireSubscription' : IDL.Func([], [Result], []),
    'fetchRSMeansBenchmarks' : IDL.Func([IDL.Text], [IDL.Text], []),
    'freezeSubscription' : IDL.Func([IDL.Principal, IDL.Text], [Result], []),
    'generateResetCode' : IDL.Func([IDL.Text], [Result_5], []),
    'generateShareLink' : IDL.Func([IDL.Text], [ShareLink], []),
    'generateUserResetCode' : IDL.Func([IDL.Text], [Result_5], []),
    'generateZoomMeeting' : IDL.Func(
        [IDL.Text, IDL.Text],
        [ZoomMeetingResult],
        [],
      ),
    'getAIAForm' : IDL.Func([IDL.Text], [IDL.Opt(AIAFormEntry)], ['query']),
    'getAIAForms' : IDL.Func([IDL.Text], [IDL.Vec(AIAFormEntry)], ['query']),
    'getActiveFilter' : IDL.Func(
        [],
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getActiveSessions' : IDL.Func([], [IDL.Vec(SessionSnapshot)], ['query']),
    'getAdminList' : IDL.Func([], [IDL.Vec(AdminRole)], ['query']),
    'getAllCancellationRequests' : IDL.Func(
        [],
        [IDL.Vec(CancellationRequest)],
        ['query'],
      ),
    'getAllUsers' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'name' : IDL.Text,
              'createdAt' : IDL.Int,
              'email' : IDL.Text,
              'lastLogin' : IDL.Int,
            })
          ),
        ],
        ['query'],
      ),
    'getAppSettings' : IDL.Func([], [AppSettings], ['query']),
    'getBankAccount' : IDL.Func([], [IDL.Opt(BankAccount)], ['query']),
    'getCertificationsForPhase' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(NCCERCertShared)],
        ['query'],
      ),
    'getComplianceItemsForPhase' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ComplianceItemShared)],
        ['query'],
      ),
    'getControllerProfile' : IDL.Func([], [Result_4], ['query']),
    'getCostCodeCompletion' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Opt(IDL.Float64)],
        ['query'],
      ),
    'getCostCodesForPhase' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Vec(CostCode__1), 'err' : IDL.Text })],
        ['query'],
      ),
    'getCriticalChangePlansForPhase' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CriticalChangePlanShared)],
        ['query'],
      ),
    'getCumulativeCashRequirement' : IDL.Func(
        [],
        [IDL.Vec(CumulativePoint)],
        ['query'],
      ),
    'getCumulativeCrashedRequirement' : IDL.Func(
        [],
        [IDL.Vec(CumulativePoint)],
        ['query'],
      ),
    'getCumulativeWithBreakdown' : IDL.Func(
        [],
        [IDL.Vec(CumulativePointWithCodes)],
        ['query'],
      ),
    'getDocumentReviewStatus' : IDL.Func(
        [],
        [IDL.Vec(VerificationDocument)],
        ['query'],
      ),
    'getDrawingNotifications' : IDL.Func(
        [],
        [IDL.Vec(DrawingNotification)],
        ['query'],
      ),
    'getDrawings' : IDL.Func([], [IDL.Vec(Drawing)], ['query']),
    'getEarnedValueMetrics' : IDL.Func(
        [BaselineType],
        [IDL.Vec(EVMPoint)],
        ['query'],
      ),
    'getFeatureLocks' : IDL.Func([], [FeatureLockSnapshot], ['query']),
    'getFilteredStandards' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Vec(SafetyStandard)],
        ['query'],
      ),
    'getIdleTimeSetting' : IDL.Func([], [IDL.Opt(IdleTimeSetting)], ['query']),
    'getLoginEmails' : IDL.Func([], [Result_3], ['query']),
    'getLoginHistory' : IDL.Func([], [IDL.Vec(SessionSnapshot)], ['query']),
    'getNCCERCertificationsForParticipant' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(NCCERCertShared)],
        ['query'],
      ),
    'getNextPayoutDate' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getOACSession' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(OACMeetingSession)],
        ['query'],
      ),
    'getOACSessions' : IDL.Func([], [IDL.Vec(OACMeetingSession)], ['query']),
    'getParticipant' : IDL.Func([IDL.Text], [IDL.Opt(Participant)], ['query']),
    'getParticipantAssignments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ParticipantAssignment)],
        ['query'],
      ),
    'getParticipantMeetingPackage' : IDL.Func(
        [IDL.Text],
        [MeetingPackage],
        ['query'],
      ),
    'getParticipants' : IDL.Func([], [IDL.Vec(Participant)], ['query']),
    'getPaymentMethods' : IDL.Func([], [IDL.Vec(PaymentMethodInfo)], ['query']),
    'getPayoutRecords' : IDL.Func([], [IDL.Vec(PayoutRecord)], ['query']),
    'getPhaseAllocations' : IDL.Func([], [IDL.Vec(PhaseAllocation)], ['query']),
    'getPhaseAllocationsByPhase' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PhaseAllocation)],
        ['query'],
      ),
    'getPhaseAllocationsByResource' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PhaseAllocation)],
        ['query'],
      ),
    'getPhaseComplianceStatus' : IDL.Func(
        [IDL.Text],
        [PhaseComplianceSummary],
        ['query'],
      ),
    'getPhases' : IDL.Func([], [IDL.Vec(Phase)], ['query']),
    'getProjectCategories' : IDL.Func(
        [],
        [IDL.Vec(ProjectCategory)],
        ['query'],
      ),
    'getProjectEVMSummary' : IDL.Func(
        [BaselineType],
        [ProjectEVMSummary],
        ['query'],
      ),
    'getProjectShareLinks' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ShareLink)],
        ['query'],
      ),
    'getProjectSubtopic' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(ProjectSubtopic)],
        ['query'],
      ),
    'getRSMeansSettings' : IDL.Func([], [RSMeansSettings], ['query']),
    'getReminderState' : IDL.Func([], [IDL.Opt(ReminderState)], ['query']),
    'getRenewalHistory' : IDL.Func(
        [],
        [IDL.Vec(RenewalHistoryEntry)],
        ['query'],
      ),
    'getResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
    'getResourcesByType' : IDL.Func(
        [ResourceType],
        [IDL.Vec(Resource)],
        ['query'],
      ),
    'getReviewRequests' : IDL.Func([], [IDL.Vec(ReviewRequest)], ['query']),
    'getScenario' : IDL.Func([IDL.Text], [IDL.Opt(Scenario)], ['query']),
    'getScenarioBenchmarkVariances' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ScenarioBenchmarkVariance)],
        ['query'],
      ),
    'getScenarioCashProjection' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ScenarioCashProjection)],
        ['query'],
      ),
    'getScenarioEVMSummary' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ScenarioEVMSummary)],
        ['query'],
      ),
    'getShareLink' : IDL.Func([IDL.Text], [IDL.Opt(ShareLink)], ['query']),
    'getSignOffsForPhase' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PhaseSignOffShared)],
        ['query'],
      ),
    'getStandard' : IDL.Func([IDL.Text], [IDL.Opt(SafetyStandard)], ['query']),
    'getStandardsForCsiCode' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SafetyStandard)],
        ['query'],
      ),
    'getStandardsForPhase' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SafetyStandard)],
        ['query'],
      ),
    'getSubscriptionStatus' : IDL.Func([], [SubscriptionStatus], ['query']),
    'getTrialLinks' : IDL.Func([], [IDL.Vec(TrialLink)], ['query']),
    'getUserCancellationRequests' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CancellationRequest)],
        ['query'],
      ),
    'getUserLoginEmails' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getUserSubscription' : IDL.Func(
        [],
        [IDL.Opt(UserSubscription)],
        ['query'],
      ),
    'getZoomSettings' : IDL.Func([], [IDL.Opt(ZoomSettings)], ['query']),
    'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isController' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isPhaseSignedOff' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isPlanFullyApproved' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'linkStandardToPhase' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [PhaseStandardLink],
        [],
      ),
    'listScenarios' : IDL.Func([], [IDL.Vec(ScenarioSummary)], ['query']),
    'registerEmailUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'rejectParticipant' : IDL.Func([IDL.Text], [IDL.Opt(Participant)], []),
    'removeLoginEmail' : IDL.Func([IDL.Text], [Result], []),
    'removeParticipantAssignment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'removeUserLoginEmail' : IDL.Func([IDL.Text], [Result], []),
    'renewSubscription' : IDL.Func([], [Result_1], []),
    'resendPasscode' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'revokeAdmin' : IDL.Func([IDL.Principal], [Result], []),
    'saveAIAForm' : IDL.Func(
        [IDL.Text, FormType, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)), IDL.Text],
        [IDL.Text],
        [],
      ),
    'saveAppSettings' : IDL.Func([AppSettings], [AppSettings], []),
    'saveBankAccount' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'savePayoutRecords' : IDL.Func([IDL.Vec(PayoutRecord)], [], []),
    'saveRSMeansSettings' : IDL.Func([RSMeansSettings], [RSMeansSettings], []),
    'saveZoomSettings' : IDL.Func([ZoomSettings], [IDL.Bool], []),
    'searchStandards' : IDL.Func(
        [IDL.Text, IDL.Opt(StandardCategory), IDL.Opt(IDL.Text)],
        [IDL.Vec(SafetyStandard)],
        ['query'],
      ),
    'setActiveFilter' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'setFeatureLock' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setFixedZoomLink' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'setIdleTimeSetting' : IDL.Func([IdleTimeMode], [IdleTimeSetting], []),
    'setNextPayoutDate' : IDL.Func([IDL.Text], [], []),
    'setPhases' : IDL.Func([IDL.Vec(PhaseInput)], [], []),
    'setReminderEmailSent' : IDL.Func([IDL.Nat], [], []),
    'setStripeSecretKey' : IDL.Func([IDL.Text], [], []),
    'submitCancellationRequest' : IDL.Func(
        [IDL.Text, IDL.Text],
        [Result_2],
        [],
      ),
    'submitDocumentForReview' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [VerificationDocument],
        [],
      ),
    'submitPhaseSignOff' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Text],
        [PhaseSignOffShared],
        [],
      ),
    'submitPlanForApproval' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CriticalChangePlanShared)],
        [],
      ),
    'switchTrialTier' : IDL.Func([SubscriptionTier], [Result_1], []),
    'testRSMeansConnection' : IDL.Func([], [IDL.Text], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unfreezeSubscription' : IDL.Func([IDL.Principal], [Result], []),
    'unlinkStandardFromPhase' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateAIAForm' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        [IDL.Bool],
        [],
      ),
    'updateControllerProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'updateCostCodeCompletion' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Float64],
        [],
        [],
      ),
    'updateCriticalChangePlan' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Vec(IDL.Text)),
          IDL.Opt(IDL.Vec(IDL.Text)),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Vec(IDL.Text)),
          IDL.Opt(IDL.Vec(IDL.Text)),
        ],
        [IDL.Opt(CriticalChangePlanShared)],
        [],
      ),
    'updateNCCERCertification' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Int),
          IDL.Opt(NCCERCertStatus),
        ],
        [IDL.Opt(NCCERCertShared)],
        [],
      ),
    'updateOACSessionZoomLink' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateParticipant' : IDL.Func([Participant], [IDL.Opt(Participant)], []),
    'updateRSMeansEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ParticipantAssignment],
        [IDL.Opt(ParticipantAssignment)],
        [],
      ),
    'updateReviewRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(ReviewRequest)],
        [],
      ),
    'updateScenario' : IDL.Func(
        [IDL.Text, CreateScenarioRequest],
        [IDL.Variant({ 'ok' : Scenario, 'err' : IDL.Text })],
        [],
      ),
    'upsertComplianceItem' : IDL.Func(
        [IDL.Text, IDL.Text, ComplianceStatus, ComplianceSeverity, IDL.Text],
        [ComplianceItemShared],
        [],
      ),
    'upsertCostCode' : IDL.Func(
        [IDL.Nat, CostCodeInput],
        [IDL.Variant({ 'ok' : CostCode__1, 'err' : IDL.Text })],
        [],
      ),
    'upsertPhase' : IDL.Func([IDL.Nat, PhaseInput], [Phase], []),
    'upsertPhaseAllocation' : IDL.Func(
        [PhaseAllocationInput],
        [PhaseAllocation],
        [],
      ),
    'upsertResource' : IDL.Func([ResourceInput], [Resource], []),
    'validateResetCode' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'zoomTransform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };